var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(e){var l=0;return function(){return l<e.length?{done:!1,value:e[l++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,l,b){e!=Array.prototype&&e!=Object.prototype&&(e[l]=b.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(e,l){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:l})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function e(b){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(b||"")+"_"+l++,b)}var l=0;return e}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.asyncIterator;e||(e=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};
$jscomp.makeIterator=function(e){var l="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return l?l.call(e):$jscomp.arrayIterator(e)};$jscomp.polyfill=function(e,l,b,n){if(l){b=$jscomp.global;e=e.split(".");for(n=0;n<e.length-1;n++){var k=e[n];k in b||(b[k]={});b=b[k]}e=e[e.length-1];n=b[e];l=l(n);l!=n&&null!=l&&$jscomp.defineProperty(b,e,{configurable:!0,writable:!0,value:l})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(e){function l(){this.batch_=null}function b(a){return a instanceof k?a:new k(function(f,b){f(a)})}if(e&&!$jscomp.FORCE_POLYFILL_PROMISE)return e;l.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(a)};var n=$jscomp.global.setTimeout;l.prototype.asyncExecuteFunction=function(a){n(a,0)};l.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var f=0;f<a.length;++f){var b=a[f];a[f]=null;try{b()}catch(p){this.asyncThrow_(p)}}}this.batch_=null};l.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var k=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{a(f.resolve,f.reject)}catch(h){f.reject(h)}};k.prototype.createResolveAndReject_=function(){function a(a){return function(h){b||(b=!0,a.call(f,h))}}var f=this,b=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};k.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof k)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var f=null!=a;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};k.prototype.resolveToNonPromiseObj_=function(a){var f=void 0;try{f=a.then}catch(h){this.reject_(h);return}"function"==typeof f?
this.settleSameAsThenable_(f,a):this.fulfill_(a)};k.prototype.reject_=function(a){this.settle_(2,a)};k.prototype.fulfill_=function(a){this.settle_(1,a)};k.prototype.settle_=function(a,f){if(0!=this.state_)throw Error("Cannot settle("+a+", "+f+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=f;this.executeOnSettledCallbacks_()};k.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)t.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var t=new l;k.prototype.settleSameAsPromise_=function(a){var f=this.createResolveAndReject_();a.callWhenSettled_(f.resolve,f.reject)};k.prototype.settleSameAsThenable_=function(a,f){var b=this.createResolveAndReject_();try{a.call(f,b.resolve,b.reject)}catch(p){b.reject(p)}};k.prototype.then=function(a,f){function b(a,f){return"function"==typeof a?function(f){try{e(a(f))}catch(r){g(r)}}:f}var e,g,u=new k(function(a,f){e=a;g=f});this.callWhenSettled_(b(a,e),b(f,g));return u};
k.prototype.catch=function(a){return this.then(void 0,a)};k.prototype.callWhenSettled_=function(a,f){function b(){switch(e.state_){case 1:a(e.result_);break;case 2:f(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?t.asyncExecute(b):this.onSettledCallbacks_.push(b)};k.resolve=b;k.reject=function(a){return new k(function(f,b){b(a)})};k.race=function(a){return new k(function(f,h){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())b(g.value).callWhenSettled_(f,
h)})};k.all=function(a){var f=$jscomp.makeIterator(a),h=f.next();return h.done?b([]):new k(function(a,e){function g(f){return function(b){q[f]=b;m--;0==m&&a(q)}}var q=[],m=0;do q.push(void 0),m++,b(h.value).callWhenSettled_(g(q.length-1),e),h=f.next();while(!h.done)})};return k},"es6","es3");$jscomp.findInternal=function(e,l,b){e instanceof String&&(e=String(e));for(var n=e.length,k=0;k<n;k++){var t=e[k];if(l.call(b,t,k,e))return{i:k,v:t}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,b){return $jscomp.findInternal(this,e,b).v}},"es6","es3");
document.addEventListener("DOMContentLoaded",function(){function e(a,f){if("js"==f){var b=document.createElement("script");b.setAttribute("async","");b.setAttribute("defer","");b.setAttribute("crossorigin","anonymous");b.setAttribute("src",a)}else"css"==f&&(b=document.createElement("link"),b.setAttribute("async",""),b.setAttribute("rel","stylesheet"),b.setAttribute("crossorigin","anonymous"),b.setAttribute("href",a));void 0!==b&&document.getElementsByTagName("head")[0].appendChild(b)}function l(){dataLayer.push(arguments)}
var b=b||{};b.scope={};b.arrayIteratorImpl=function(a){var f=0;return function(){return f<a.length?{done:!1,value:a[f++]}:{done:!0}}};b.arrayIterator=function(a){return{next:b.arrayIteratorImpl(a)}};b.makeIterator=function(a){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var f="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return f?f.call(a):b.arrayIterator(a)};b.getGlobal=function(a){return"undefined"!=typeof window&&
window===a?a:"undefined"!=typeof global&&null!=global?global:a};b.global=b.getGlobal(this);b.ASSUME_ES5=!1;b.ASSUME_NO_NATIVE_MAP=!1;b.ASSUME_NO_NATIVE_SET=!1;b.SIMPLE_FROUND_POLYFILL=!1;b.defineProperty=b.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,b){a!=Array.prototype&&a!=Object.prototype&&(a[f]=b.value)};b.polyfill=function(a,f,e,p){if(f){e=b.global;a=a.split(".");for(p=0;p<a.length-1;p++){var h=a[p];h in e||(e[h]={});e=e[h]}a=a[a.length-1];p=e[a];
f=f(p);f!=p&&null!=f&&b.defineProperty(e,a,{configurable:!0,writable:!0,value:f})}};b.FORCE_POLYFILL_PROMISE=!1;b.polyfill("Promise",function(a){function f(){this.batch_=null}function e(a){return a instanceof g?a:new g(function(b,f){b(a)})}if(a&&!b.FORCE_POLYFILL_PROMISE)return a;f.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var p=b.global.setTimeout;f.prototype.asyncExecuteFunction=
function(a){p(a,0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var f=a[b];a[b]=null;try{f()}catch(r){this.asyncThrow_(r)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var g=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(v){b.reject(v)}};g.prototype.createResolveAndReject_=
function(){function a(a){return function(m){f||(f=!0,a.call(b,m))}}var b=this,f=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};g.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof g)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};g.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(v){this.reject_(v);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};g.prototype.reject_=function(a){this.settle_(2,a)};g.prototype.fulfill_=function(a){this.settle_(1,a)};g.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var k=new f;g.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};g.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(r){f.reject(r)}};g.prototype.then=function(a,b){function f(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(w){m(w)}}:
b}var e,m,h=new g(function(a,b){e=a;m=b});this.callWhenSettled_(f(a,e),f(b,m));return h};g.prototype.catch=function(a){return this.then(void 0,a)};g.prototype.callWhenSettled_=function(a,b){function f(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?k.asyncExecute(f):this.onSettledCallbacks_.push(f)};g.resolve=e;g.reject=function(a){return new g(function(b,f){f(a)})};g.race=function(a){return new g(function(f,
h){for(var m=b.makeIterator(a),g=m.next();!g.done;g=m.next())e(g.value).callWhenSettled_(f,h)})};g.all=function(a){var f=b.makeIterator(a),h=f.next();return h.done?e([]):new g(function(a,b){function m(b){return function(f){g[b]=f;r--;0==r&&a(g)}}var g=[],r=0;do g.push(void 0),r++,e(h.value).callWhenSettled_(m(g.length-1),b),h=f.next();while(!h.done)})};return g},"es6","es3");b.SYMBOL_PREFIX="jscomp_symbol_";b.initSymbol=function(){b.initSymbol=function(){};b.global.Symbol||(b.global.Symbol=b.Symbol)};
b.SymbolClass=function(a,f){this.j=a;b.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.SymbolClass.prototype.toString=function(){return this.j};b.Symbol=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new b.SymbolClass(b.SYMBOL_PREFIX+(e||"")+"_"+f++,e)}var f=0;return a}();b.initSymbolIterator=function(){b.initSymbol();var a=b.global.Symbol.iterator;a||(a=b.global.Symbol.iterator=b.global.Symbol("Symbol.iterator"));
"function"!=typeof Array.prototype[a]&&b.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return b.iteratorPrototype(b.arrayIteratorImpl(this))}});b.initSymbolIterator=function(){}};b.initSymbolAsyncIterator=function(){b.initSymbol();var a=b.global.Symbol.asyncIterator;a||(a=b.global.Symbol.asyncIterator=b.global.Symbol("Symbol.asyncIterator"));b.initSymbolAsyncIterator=function(){}};b.iteratorPrototype=function(a){b.initSymbolIterator();a={next:a};a[b.global.Symbol.iterator]=
function(){return this};return a};b.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(h){}return!1};b.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:b.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;b.generator={};b.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");
};b.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};b.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};b.generator.Context.prototype.stop_=function(){this.isRunning_=!1};b.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||
this.finallyAddress_};b.generator.Context.prototype.next_=function(a){this.yieldResult=a};b.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};b.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};b.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};b.generator.Context.prototype.yield=
function(a,b){this.nextAddress=b;return{value:a}};b.generator.Context.prototype.yieldAll=function(a,f){a=b.makeIterator(a);var e=a.next();b.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=f;else return this.yieldAllIterator_=a,this.yield(e.value,f)};b.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};b.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};b.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=
a;void 0!=b&&(this.finallyAddress_=b)};b.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};b.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};b.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};b.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:
this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};b.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};b.generator.Context.prototype.forIn=
function(a){return new b.generator.Context.PropertyIterator(a)};b.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};b.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};b.generator.Engine_=function(a){this.context_=new b.generator.Context;this.program_=a};b.generator.Engine_.prototype.next_=
function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};b.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};b.generator.Engine_.prototype.throw_=
function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};b.generator.Engine_.prototype.yieldAllStep_=function(a,f,e){try{var h=a.call(this.context_.yieldAllIterator_,f);b.generator.ensureIteratorResultIsObject_(h);if(!h.done)return this.context_.stop_(),h;var g=h.value}catch(u){return this.context_.yieldAllIterator_=null,this.context_.throw_(u),this.nextStep_()}this.context_.yieldAllIterator_=
null;e.call(this.context_,g);return this.nextStep_()};b.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(f){this.context_.yieldResult=void 0,this.context_.throw_(f)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,
done:!0}};b.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};b.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};b.generator.createGenerator=function(a,f){f=new b.generator.Generator_(new b.generator.Engine_(f));b.setPrototypeOf&&b.setPrototypeOf(f,a.prototype);return f};b.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}
function e(b){return a.throw(b)}return new Promise(function(f,g){function h(a){a.done?f(a.value):Promise.resolve(a.value).then(b,e).then(h,g)}h(a.next())})};b.asyncExecutePromiseGeneratorFunction=function(a){return b.asyncExecutePromiseGenerator(a())};b.asyncExecutePromiseGeneratorProgram=function(a){return b.asyncExecutePromiseGenerator(new b.generator.Generator_(new b.generator.Engine_(a)))};b.findInternal=function(a,b,e){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var h=
a[g];if(b.call(e,h,g,a))return{i:g,v:h}}return{i:-1,v:void 0}};b.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return b.findInternal(this,a,e).v}},"es6","es3");e("https://cdn.jsdelivr.net/gh/amp-blogs/allazodiacs/cssv0.3.css","css","css");e("https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js","js");e("https://cdn.jsdelivr.net/gh/amp-blogs/allazodiacs/main.min.js","js");"https://all-about-zodiac-signs.blogspot.com/?m=1"!==location.href&&"https://all-about-zodiac-signs.blogspot.com/"!==
location.href||e("https://cdn.jsdelivr.net/gh/amp-blogs/allazodiacs/particle.js","js");"https://all-about-zodiac-signs.blogspot.com/?m=1"===location.href&&"https://all-about-zodiac-signs.blogspot.com/?m=1"===location.href||e("https://cdn.firebase.com/v0/firebase.js","js");wpac_init=window.wpac_init||[];wpac_init.push({widget:"Rating",id:21956});(function(){if(!("WIDGETPACK_LOADED"in window)){WIDGETPACK_LOADED=!0;var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.defer=!0;
a.src="https://cdn.jsdelivr.net/gh/amp-blogs/allazodiacs/wpack.widget.min.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b.nextSibling)}})();var n=!1;window.addEventListener("scroll",function(){if(0!=document.documentElement.scrollTop&&!1===n||0!=document.body.scrollTop&&!1===n){var a=document.createElement("script");a.async=!0;a.src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,
b);!0;n=!0}},!0);(adsbygoogle=window.adsbygoogle||[]).push({google_ad_client:"ca-pub-1516488007351930",enable_page_level_ads:!0});document.readyState&&(document.onreadystatechange=function(){document.querySelector(".preloader").style.display="none";if("loaded"==document.readyState||"complete"==document.readyState)jQuery.each($("span[id]"),function(a,b){function f(a){ret="";for(var b=a.childNodes.length,e=0;e<b;e++){var g=a.childNodes[e];8!=g.nodeType&&(ret+=1!=g.nodeType?g.nodeValue:f(g))}return ret}
if("https://all-about-zodiac-signs.blogspot.com/?m=1"!==location.href||"https://all-about-zodiac-signs.blogspot.com/?m=1"!==location.href){a=f(document.getElementById("main-body")).split(" ").length;a=Math.round(a/200);document.getElementById("r-time").innerHTML=+a+"' read";var e=$(b).parent().find(".postviews"),g=new Firebase("https://aazs-17bc0.firebaseio.com/pages/id/"+$(b).attr("id"));g.once("value",function(a){var f=!1;null==(a=a.val())&&((a={value:0}).url=window.location.href,a.id=$(b).attr("id"),
f=!0);e.text(a.value);a.value++;"/"!=window.location.pathname&&(f?g.set(a):g.child("value").set(a.value))})}}),jQuery.cookie=function(a,b,e){if(1<arguments.length&&"[object Object]"!==String(b)){if(e=jQuery.extend({},e),null==b&&(e.expires=-1),"number"==typeof e.expires){var f=e.expires,g=e.expires=new Date;g.setDate(g.getDate()+f)}return b=String(b),document.cookie=[encodeURIComponent(a),"=",e.raw?b:encodeURIComponent(b),e.expires?"; expires="+e.expires.toUTCString():"",e.path?"; path="+e.path:"",
e.domain?"; domain="+e.domain:"",e.secure?"; secure":""].join("")}return g=(e=b||{}).raw?function(a){return a}:decodeURIComponent,(f=(new RegExp("(?:^|; )"+encodeURIComponent(a)+"=([^;]*)")).exec(document.cookie))?g(f[1]):null},jQuery(document).ready(function(a){"yes"!=a.cookie("popup-email-box")&&(a(".outer-email-popup-box").delay(15E3).fadeIn("fast"),a(".exit-button-subbox, .button").click(function(){a(".outer-email-popup-box").stop().fadeOut("fast")}));a.cookie("popup-email-box","yes",{path:"/",
expires:1})}),!function(){if(-1!==location.search.indexOf("fbclid=")){var a="";try{var b=new URL(location);b.searchParams.delete("fbclid");a=b.href}catch(h){a=location.search.replace(/[?&]fbclid=.*$/,""),a=location.pathname+a+location.hash}history.replaceState(null,"",a)}}()});(function(a){function b(){document.getElementById("offcanvas").style.background="url('https://2.bp.blogspot.com/-qVGSlJ6VQ4A/W5TJ4QuhgxI/AAAAAAAAKHw/iINNWU7Um1QH5nwtNIjwKqd5-qeW1ReWQCLcBGAs/h767-w360/menu-bg.webp')";document.getElementById("offcanvas").style.backgroundSize=
"cover"}a.addEventListener?a.addEventListener("load",b,!1):a.attachEvent&&a.attachEvent("onload",b)})(window,document,"script");window.dataLayer=window.dataLayer||[];l("js",new Date);l("config","UA-92570002-1");for(var k="",t=0;12>t;t++)k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));window[""+k]=function(){function a(a){var b="";a=a||30;for(var e=0;e<a;e++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*
Math.random()));return b}var b={t$:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var e,f,g="",m=0;for(a=b.e$(a);m<a.length;){var h=(e=a.charCodeAt(m++))>>2;var k=(3&e)<<4|(e=a.charCodeAt(m++))>>4;var l=(15&e)<<2|(f=a.charCodeAt(m++))>>6;var p=63&f;isNaN(e)?l=p=64:isNaN(f)&&(p=64);g=g+this.t$.charAt(h)+this.t$.charAt(k)+this.t$.charAt(l)+this.t$.charAt(p)}return g},decode:function(a){var e,f,g,m="",h=0;for(a=a.replace(/[^A-Za-z0-9\+\/=]/g,"");h<a.length;){var k=
this.t$.indexOf(a.charAt(h++))<<2|(e=this.t$.indexOf(a.charAt(h++)))>>4;e=(15&e)<<4|(f=this.t$.indexOf(a.charAt(h++)))>>2;var l=(3&f)<<6|(g=this.t$.indexOf(a.charAt(h++)));m+=String.fromCharCode(k);64!=f&&(m+=String.fromCharCode(e));64!=g&&(m+=String.fromCharCode(l))}return b.n$(m)},e$:function(a){a=a.replace(/;/g,";");for(var b="",e=0;e<a.length;e++){var f=a.charCodeAt(e);128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>
6&63|128)),b+=String.fromCharCode(63&f|128))}return b},n$:function(a){for(var b="",e=0,f=c1=c2=0;e<a.length;)128>(f=a.charCodeAt(e))?(b+=String.fromCharCode(f),e++):191<f&&224>f?(c2=a.charCodeAt(e+1),b+=String.fromCharCode((31&f)<<6|63&c2),e+=2):(c2=a.charCodeAt(e+1),c3=a.charCodeAt(e+2),b+=String.fromCharCode((15&f)<<12|(63&c2)<<6|63&c3),e+=3);return b}},e="YWQtbGVmdA== YWRCYW5uZXJXcmFw YWQtZnJhbWU= YWQtaGVhZGVy YWQtaW1n YWQtaW5uZXI= YWQtbGFiZWw= YWQtbGI= YWQtZm9vdGVy YWQtY29udGFpbmVy YWQtY29udGFpbmVyLTE= YWQtY29udGFpbmVyLTI= QWQzMDB4MTQ1 QWQzMDB4MjUw QWQ3Mjh4OTA= QWRBcmVh QWRGcmFtZTE= QWRGcmFtZTI= QWRGcmFtZTM= QWRGcmFtZTQ= QWRMYXllcjE= QWRMYXllcjI= QWRzX2dvb2dsZV8wMQ== QWRzX2dvb2dsZV8wMg== QWRzX2dvb2dsZV8wMw== QWRzX2dvb2dsZV8wNA== RGl2QWQ= RGl2QWQx RGl2QWQy RGl2QWQz RGl2QWRB RGl2QWRC RGl2QWRD QWRJbWFnZQ== QWREaXY= QWRCb3gxNjA= QWRDb250YWluZXI= Z2xpbmtzd3JhcHBlcg== YWRUZWFzZXI= YmFubmVyX2Fk YWRCYW5uZXI= YWRiYW5uZXI= YWRBZA== YmFubmVyYWQ= IGFkX2JveA== YWRfY2hhbm5lbA== YWRzZXJ2ZXI= YmFubmVyaWQ= YWRzbG90 cG9wdXBhZA== YWRzZW5zZQ== Z29vZ2xlX2Fk b3V0YnJhaW4tcGFpZA== c3BvbnNvcmVkX2xpbms=".split(" "),
l=b.decode(e[Math.floor(Math.random()*e.length)]),g=0,n="moc.kcolbdakcolb",q=0;a();return{IZsqxBSFIK:function(a,b){var e,f,g,h,k;void 0!==document.body&&(b=l,(e=document.createElement("DIV")).id=b,e.style.position="absolute",e.style.left="-5000px",e.style.top="-5000px",e.style.height="60px",e.style.width="468px",f=document.body.childNodes,15<(g=Math.floor(f.length/2))?((h=document.createElement("div")).style.position="absolute",h.style.height="0px",h.style.width="0px",h.style.top="-5000px",h.style.left=
"-5000px",document.body.insertBefore(h,document.body.childNodes[g]),h.appendChild(e),(k=document.createElement("DIV")).id="banner_ad",k.style.position="absolute",k.style.left="-5000px",k.style.top="-5000px",document.body.appendChild(k)):(e.id="banner_ad",document.body.appendChild(e)),q=setInterval(function(){e?(a(0==e.clientHeight,"0.1"),a(0==e.clientWidth,"0.1"),a("hidden"==e.display,"0.1"),a("none"==e.visibility,"0.1"),a(0==e.opacity,"0.1")):a(!0,"0.1")},1E3))},OJqHUJXpcm:function(a,e){a&&0==g?
(g=1,window[""+k].sXmFpnsxyg(),window[""+k].OJqHUJXpcm=function(){}):(a=b.decode("aW5zLmFkc2J5Z29vZ2xl"),document.querySelector(a))},sXmFpnsxyg:function(){var e,f="Ly95dWkueWFob29hcGlzLmNvbS8zLjE4LjEvYnVpbGQvY3NzcmVzZXQvY3NzcmVzZXQtbWluLmNzcw==";!function(a){a=a&&a.substr(a.length-15);var b=document.styleSheets;for(x=0;x<b.length;){if(thisurl=b[x].href,thisurl=thisurl&&thisurl.substr(thisurl.length-15),thisurl===a)return 1;x++}}(f=b.decode(f))&&((e=document.createElement("link")).setAttribute("rel",
"stylesheet"),e.setAttribute("type","text/css"),e.setAttribute("href",f),document.getElementsByTagName("head")[0].appendChild(e));clearInterval(q);document.body.innerHTML="";document.body.style.cssText+="margin:0px !important";document.body.style.cssText+="padding:0px !important";e=document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth;f=window.innerHeight||document.body.clientHeight||document.documentElement.clientHeight;var g=document.createElement("DIV"),h=a();g.id=
h;g.style.position="fixed";g.style.left="0";g.style.top="0";g.style.width=e+"px";g.style.height=f+"px";g.style.backgroundColor="#ffffff";g.style.zIndex="9999";document.body.appendChild(g);g="";g=(g=g.replace("FILLVECTID1",a())).replace("FILLVECTID2",a());e=document.createElement("DIV");e.innerHTML=g;e.style.position="absolute";e.style.bottom="30px";e.style.left="30px";e.style.width="160px";e.style.height="40px";e.style.zIndex="10000";e.style.opacity=".6";e.style.cursor="pointer";e.addEventListener("click",
function(){n=n.split("").reverse().join("");window.location.href="//"+n});document.getElementById(h).appendChild(e);h=document.createElement("DIV");g=a();h.id=g;h.style.position="relative";h.style.top=f/7+"px";h.style.minHeight=f/3.5+"px";h.style.backgroundColor="#fff";h.style.zIndex="10000";h.style.cssText+="line-height: normal !important";h.style.cssText+="font-size: 16pt !important";h.style.cssText+="text-align: center !important";h.style.cssText+="padding: 12px !important";h.style.display+="block";
h.style.marginLeft="30px";h.style.marginRight="30px";h.style.borderRadius="15px";document.body.appendChild(h);h.style.boxShadow="0px 14px 24px -8px rgba(0,0,0,0.3)";h.style.visibility="visible";f=30;g=22;var k=18,l=18;(640>window.innerWidth||640>screen.width)&&(h.style.zoom="100%",h.style.cssText+="font-size: 16pt !important",h.style.marginLeft="45px;",e.style.zoom="65%",f=22,g=18,l=k=12);h.innerHTML='<h3 style="color:#999;font-size:'+f+'pt;color:#000000;font-weight:200;margin-top:10px;margin-bottom:10px;text-align:center;">Hey there.</h3><h1 style="font-size:'+
g+'pt;font-weight:500;color:#000000;margin-top:10px;margin-bottom:10px;text-align:center;">So... you use an ad blocker.  That\'s cool.  Sometimes we do to.</h1><hr style=" display: block;margin-top: 0.5em;margin-bottom: 0.5em;margin-left: auto;margin-right: auto; border:1px solid #CCC; width: 25%;text-align:center;"><p style="font-weight:300;font-size:'+k+'pt;color:#000000;text-align:center;">But without ad revenue, we wouldn\'t even be here and we might not be here much longer.</p><p aria-hidden="true" style="margin-top:35px;"><div onmouseover="this.style.opacity=.9;" onmouseout="this.style.opacity=1;"  id="'+
a()+'" style="cursor:pointer;font-size:'+l+'pt;font-family:Helvetica, geneva, sans-serif; font-weight:300;border-radius:8px;padding:10px;background-color:#ff0000;color:#ffffff;width:100%;margin:auto;margin-top:10px;margin-bottom:10px;" onclick="window.location.reload();">Please disable your ad blocker and click to continue.</div></p>'}}}();window.tmGDTIdOba=function(a,b){var e,f=Date.now,g=window.requestAnimationFrame,k=f(),l=function(){f()-k<b?e||g(l):a()};return g(l),{clear:function(){e=1}}};document.body&&
(document.body.style.visibility="visible");(function(a){function b(){document.addEventListener?(document.removeEventListener("DOMContentLoaded",k),window.removeEventListener("load",k)):(document.detachEvent("onreadystatechange",k),window.detachEvent("onload",k))}var e=!1,k=function(){e||!document.addEventListener&&"load"!==event.type&&"complete"!==document.readyState||(e=!0,b(),a())};if("complete"===document.readyState)a();else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
k),window.addEventListener("load",k);else{document.attachEvent("onreadystatechange",k);window.attachEvent("onload",k);var g=!1;try{g=null==window.frameElement&&document.documentElement}catch(u){}g&&g.doScroll&&!function q(){if(!e){try{g.doScroll("left")}catch(m){return setTimeout(q,50)}e=!0;b();a()}}()}})(function(){document.getElementById("babasbmsgx")&&(document.getElementById("babasbmsgx").style.visibility="hidden",document.getElementById("babasbmsgx").style.display="none");window.tmGDTIdOba(function(){window[""+
k].IZsqxBSFIK(window[""+k].OJqHUJXpcm,window[""+k].zMRkmfZRNX)},6E3)})})
