var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,g,f){a instanceof String&&(a=String(a));for(var b=a.length,k=0;k<b;k++){var l=a[k];if(g.call(f,l,k,a))return{i:k,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,f){a!=Array.prototype&&a!=Object.prototype&&(a[g]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,g,f,b){if(g){f=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var k=a[b];k in f||(f[k]={});f=f[k]}a=a[a.length-1];b=f[a];g=g(b);g!=b&&null!=g&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6","es3");function haveCookie(){return _$_[0]in document}
function setCookie(a,g,f){if(!haveCookie())return!1;var b=new Date;return b.setDate(b.getDate()+f),f=escape(g)+("0"==f?_$_[1]:_$_[2]+b.toUTCString())+_$_[3],document.cookie=a+_$_[4]+f,getCookie(a)===g}function testcookie(){return!!setCookie(_$_[5],_$_[6])}
function getCookie(a){if(!havecookie())return _$_[1];var g,f,b,k=document.cookie.split(_$_[7]);for(g=0;g<k.length;g++)if(f=k[g].substr(0,k[g].indexOf(_$_[4])),b=k[g].substr(k[g].indexOf(_$_[4])+1),(f=f.replace(/^\s+|\s+$/g,_$_[1]))==a)return unescape(b);return _$_[1]}function delCookie(a){setCookie(a,_$_[1],-1)}function checkLocal(){return _$_[8]!=typeof localStorage}function setLocal(a,g){return!!checkLocal()&&(localStorage.setItem(a,g),!0)}
function getLocal(a){return checkLocal()&&(a=localStorage.getItem(a))?a:_$_[1]}function delLocal(a){localStorage.removeItem(a)}function setCookieLocal(a,g){return checkLocal()?setLocal(a,g):!!testCookie()&&setCookie(a,g)}function getCookieLocal(a){return checkLocal()?getLocal(a):testCookie()?getCookie(a):_$_[1]}function delCookieLocal(a){return checkLocal()?delLocal(a):testCookie()?delCookie(a):_$_[1]}
function cmnu(a,g){var f=_$_[21]+g+_$_[22];$(_$_[35],a).each(function(){var a=$(this).text(),k=a.substr(0,1),l=a.substr(1),m=$(this).find(_$_[23]).length?_$_[24]+$(this).find(_$_[23]).attr(_$_[25])+_$_[26]:_$_[1],p=$(this).find(_$_[28]).attr(_$_[27]);f=_$_[29]==k||_$_[30]==k?f+(_$_[31]+p+_$_[22]+m+l+_$_[32]):f+(_$_[33]+p+_$_[22]+m+a+_$_[34]+g+_$_[22])});f+=_$_[36];$(a).html(f);$(_$_[37],a).each(function(){var a=$(this);"0"==a.html().replace(rgx[0],_$_[1]).length&&a.remove()});$(_$_[35],a).each(function(){var a=
$(this);"0"==a.html().replace(rgx[0],_$_[1]).length&&a.remove()})}
function lpost(a){var g=a.find(_$_[38]),f=g.html(),b=[];var k=[];b=_$_[39];var l=a.find(_$_[40]),m=a.find(_$_[41]),p=a.find(_$_[42]);k=a.find(_$_[43]).width();var u=$(_$_[45]).attr(_$_[44]);a=(q=a.find(_$_[46])).text();var q=q.find(_$_[28]).attr(_$_[27]),y=300<k?_$_[47]:_$_[48];if(m.attr(_$_[49],function(a,b){return b.replace(_$_[51],_$_[52]).replace(_$_[50],y)}),l.length&&(rgx[6].test(f)||rgx[8].test(f)?(b=rgx[6].exec(rgx[6]),k=rgx[8].exec(f),b=null!==b?b[5]:k[3],k=_$_[53]+b+_$_[52],b=_$_[54]):k=
rgx[5].test(f)?(k=rgx[5].exec(f))[4].replace(rgx[7],_$_[55]+y+_$_[55]):_$_[56],l.attr(_$_[49],_$_[56]===k?_$_[57]:k)),-1!=m.attr(_$_[49]).indexOf(_$_[58])&&(m.append(_$_[59]),m.parent(_$_[61]).addClass(_$_[60])),rgx[9].test(f)?b=_$_[54]:rgx[10].test(f)?b=_$_[62]:rgx[11].test(f)?b=_$_[63]:rgx[12].test(f)&&(b=5>=rgx[12].exec(f).index?_$_[64]:_$_[39]),p.prepend(_$_[65]+b+_$_[26]),rgx[29].test(f)&&!hrev){l=[];p=0;b=(l=f.match(rgx[29])).length;for(k=0;k<b;k++)p+=parseInt(l[k].replace(rgx[29],_$_[66]).replace(/"/g,
_$_[1]).replace(/'/g,_$_[1]));l=p/b;m.append(_$_[67]+rgx[1]+_$_[68]+l.toFixed(1)+_$_[69]);m.find(_$_[72]).css(_$_[70],10*l.toFixed(1)+_$_[71])}(f=f.replace(rgx[15],_$_[1]).replace(rgx[16],_$_[1]).replace(/"/g,_$_[73])).length>sumLength&&(f=f.substring(0,sumLength)+_$_[74]+q+_$_[75]+u+_$_[76]+a+_$_[22]+u+_$_[77]);g.html(f);m.attr(_$_[78],_$_[79]+(-1!=m.attr(_$_[49]).indexOf(_$_[80])?_$_[81]+m.attr(_$_[49])+_$_[82]:_$_[57])+_$_[83])}
function ajaxsrc(a){!function(g){var f={blogURL:_$_[1],srcBlank:_$_[56],findText:_$_[84],NotfindText:_$_[85],Showthumb:!0,LoadingText:_$_[86],viewMoreText:vmtx,scrthumbSize:50,MaxPost:10,summaryLength:100},b=(f=g.extend({},f,a),g(_$_[87])),k=b.find(_$_[88]);b.append(_$_[89]+rgx[1]+_$_[90]);var l=g(_$_[91]);b.on(_$_[92],function(){var a=k.val();return l.show().html(_$_[93]+f.LoadingText+_$_[94]),g.get((_$_[1]===f.blogURL?window.location.protocol+_$_[95]+window.location.host:f.blogURL)+_$_[96]+a+_$_[97]+
f.MaxPost,function(b){var g,k,m=b.feed.entry;if(void 0!==m){var p=_$_[98]+f.findText+_$_[99]+a+_$_[100];p+=_$_[101]+rgx[1]+_$_[102];for(var v=0,H=m.length;v<H;v++){var G=new RegExp(a,_$_[103]);var I=m[v].title.$t.replace(G,_$_[104]+a+_$_[105]);var x=m[v].link.length;for(g=0;g<x;g++)_$_[106]==m[v].link[g].rel&&(k=m[v].link[g].href);for(g=0;g<x;g++)var B=_$_[39];x=_$_[108]in m[v]?m[v].content.$t:_$_[109]in m[v]?m[v].summary.$t:_$_[1];_$_[110]in m[v]?(g=m[v].media$thumbnail.url.replace(rgx[7],_$_[111]+
f.scrthumbSize+_$_[112]),-1!=m[v].media$thumbnail.url.indexOf(_$_[58])&&(g=m[v].media$thumbnail.url.replace(_$_[113],_$_[114]),B=_$_[54])):rgx[6].test(x)||rgx[8].test(x)?(B=rgx[6].exec(rgx[6]),g=rgx[8].exec(x),g=_$_[53]+(null!==B?B[5]:g[3])+_$_[52],B=_$_[54]):g=rgx[5].test(x)?(g=rgx[5].exec(x))[4].replace(rgx[7],_$_[111]+f.scrthumbSize+_$_[112]):f.srcBlank;rgx[9].test(x)?B=_$_[54]:rgx[10].test(x)?B=_$_[62]:rgx[11].test(x)?B=_$_[63]:rgx[12].test(x)&&(B=5>=rgx[12].exec(x).index?_$_[64]:_$_[39]);(x=
x.replace(rgx[15],_$_[1]).replace(/"/g,_$_[73]).replace(rgx[16],_$_[1])).length>f.summaryLength&&(x=x.substring(0,f.summaryLength)+_$_[115]);x=x.replace(G,_$_[104]+a+_$_[105]);p+=_$_[116]+rgx[30]+_$_[117]+(_$_[56]===g?_$_[57]:_$_[118]+g+_$_[119])+_$_[120]+k+_$_[121]+B+_$_[122]+rgx[32]+_$_[123]+k+_$_[22]+I+_$_[77]+(0<f.summaryLength?_$_[124]+x+_$_[125]:_$_[1])+_$_[94]}p+=_$_[94]+(b.feed.openSearch$totalResults.$t>b.feed.openSearch$itemsPerPage.$t?_$_[126]+a+_$_[22]+f.viewMoreText+_$_[99]+a+_$_[127]:
_$_[1]);l.html(p)}else l.html(_$_[128]+f.NotfindText+_$_[129])},_$_[130]),!1});b.on(_$_[9],_$_[131],function(){return l.fadeOut(),!1})}(jQuery)}
function vmode(a){function g(){return k.removeClass(_$_[132]).addClass(_$_[139]),l.removeClass(_$_[18]),m.addClass(_$_[18]),setCookieLocal(b.clist,null,1E4),delCookieLocal(b.cgrid),!1}var f=jQuery;var b={viewdefault:_$_[132],clist:_$_[133],cgrid:_$_[134]};b=f.extend({},b,a);var k=f(_$_[136]).find(_$_[135]);var l=f(_$_[137]);var m=f(_$_[138]);f=function(){return k.addClass(_$_[132]).removeClass(_$_[139]),l.addClass(_$_[18]),m.removeClass(_$_[18]),setCookieLocal(b.cgrid,null,1E4),delCookieLocal(b.clist),
!1};getCookieLocal(b.clist)&&_$_[132]!=b.viewdefault?(g(),delCookieLocal(b.clist)):getCookieLocal(b.cgrid)&&_$_[132]!=b.viewdefault?(f(),delCookieLocal(b.cgrid)):getCookieLocal(b.clist)?(g(),delCookieLocal(b.clist)):getCookieLocal(b.cgrid)?(f(),delCookieLocal(b.cgrid)):_$_[132]!=b.viewdefault?(g(),delCookieLocal(b.clist)):(f(),delCookieLocal(b.cgrid));l.click(f);m.click(g)}
function cdate(){$(_$_[146]).each(function(){var a=$(this).attr(_$_[44]),g=mName;if(_$_[1]!=a)var f=(b=a.substring(0,10)).substring(0,4),b=(a=b.substring(5,7),b.substring(8,10)),k=g[parseInt(a,10)-1];$(this).parents(_$_[145]).find(_$_[144]).html(_$_[140]+b+_$_[141]+k+_$_[142]+f+_$_[143])})}
function lMore(a){var g=jQuery;g.extend({},{olderPostsLink:_$_[1],loadMoreDiv:null,thumbnailSize:400,summaryLength:100,postContainerSelector:_$_[154],MoreText:lmtx,viewdefault:_$_[132],clist:_$_[133],cgrid:_$_[155],loading:!1},a);g(window);g(document)}
function pageNavi(a){!function(g){function f(a){(function(a){var b="";number=parseInt(q.numshowpage/2);number==q.numshowpage-number&&(q.numshowpage=2*number+1);start=p-number;1>start&&(start=1);maxlen=parseInt(a/q.postperpage)+1;maxlen-1==a/q.postperpage&&--maxlen;akhir=start+q.numshowpage-1;akhir>maxlen&&(akhir=maxlen);a=parseInt(p)-1;1<p&&(b=2==p?"page"==m?b+'<span class="showpage"><a href="">'+q.previous+"</a></span>":b+'<span class="showpageNum"><a href="/search/label/'+u+"?&max-results="+q.postperpage+
'">'+q.previous+"</a></span>":"page"==m?b+'<span class="showpageNum"><a class="xpagex" href="#" alt="'+a+'">'+q.previous+"</a></span>":b+'<span class="showpageNum"><a class="xlabelx" href="#" alt="'+a+'">'+q.previous+"</a></span>");1<start&&(b="page"==m?b+'<span class="showpageNum"><a href="">1</a></span>':b+'<span class="showpageNum"><a href="/search/label/'+u+"?&max-results="+q.postperpage+'">1</a></span>');2<start&&(b+='<span class="dotxpage"> ...  </span>');for(a=start;a<=akhir;a++)b=p==a?b+'<span class="showpagePoint">'+
a+"</span>":1==a?"page"==m?b+'<span class="showpageNum"><a href="">1</a></span>':b+'<span class="showpageNum"><a href="/search/label/'+u+"?&max-results="+q.postperpage+'">1</a></span>':"page"==m?b+'<span class="showpageNum"><a href="#" class="xpagex" alt="'+a+'">'+a+"</a></span>":b+'<span class="showpageNum"><a href="#" class="xlabelx" alt="'+a+'">'+a+"</a></span>";akhir<maxlen-1&&(b+='<span class="dotxpage"> ... </span>');akhir<maxlen&&(b="page"==m?b+'<span class="showpageNum"><a href="#" class="xpagex" alt="'+
maxlen+'">'+maxlen+"</a></span>":b+'<span class="showpageNum"><a href="#" class="xlabelx" alt="'+maxlen+'">'+maxlen+"</a></span>");a=parseInt(p)+1;p<maxlen&&(b="page"==m?b+'<span class="showpageNum"><a href="#" class="xpagex" alt="'+a+'">'+q.next+"</a></span>":b+'<span class="showpageNum"><a href="#" class="xlabelx" alt="'+a+'">'+q.next+"</a></span>");a=document.getElementsByName("pageArea");for(var f=document.getElementById("blog-pagerindex"),l=0;l<a.length;l++)a[l].innerHTML=b;a&&0<a.length&&(b=
"");f&&(f.innerHTML=b);g(".blog-pagerindex").css("display","table");g(q.container).removeClass("load-next");g(".blog-pagerindex a.xpagex, .blog-pagerindex a.xlabelx").click(function(){g(q.container).addClass("load-next");g(".hfeed .loader").show();var a=g(this).attr("alt");return jsonstart=(a-1)*q.postperpage,k=a,"page"==m?g.get(y+"/feeds/posts/summary?start-index="+jsonstart+"&max-results=1&alt=json-in-script",v,"jsonp"):g.get(y+"/feeds/posts/summary/-/"+u+"?start-index="+jsonstart+"&max-results=1&alt=json-in-script",
v,"jsonp"),!1})})(a=parseInt(a.feed.openSearch$totalResults.$t,10))}function b(){var a=z;-1!=a.indexOf("/search/label/")&&(u=-1!=a.indexOf("?updated-max")?a.substring(a.indexOf("/search/label/")+14,a.indexOf("?updated-max")):-1!=a.indexOf("?max")?a.substring(a.indexOf("/search/label/")+14,a.indexOf("?max")):-1!=a.indexOf("?&max")?a.substring(a.indexOf("/search/label/")+14,a.indexOf("?&max")):a.substr(a.lastIndexOf("/")));-1==a.indexOf("?q=")&&-1==a.indexOf(".html")&&(-1==a.indexOf("/search/label/")?
(m="page",-1!=a.indexOf("max-results=")&&-1!=a.indexOf("#PageNo=")?q.postperpage=a.substring(a.indexOf("max-results=")+12,a.indexOf("#PageNo=")):-1!=a.indexOf("max-results=")?q.postperpage=a.substring(a.indexOf("max-results=")+12):q.postperpage=q.postperpage,p=-1!=z.indexOf("#PageNo=")?z.substring(z.indexOf("#PageNo=")+8,z.length):1,g.get(y+"/feeds/posts/summary?max-results=1&alt=json-in-script",f,"jsonp")):(m="label",-1!=a.indexOf("max-results=")&&-1!=a.indexOf("#PageNo=")?q.postperpage=a.substring(a.indexOf("max-results=")+
12,a.indexOf("#PageNo=")):-1!=a.indexOf("max-results=")?q.postperpage=a.substring(a.indexOf("max-results=")+12):q.postperpage=q.postperpage,p=-1!=z.indexOf("#PageNo=")?z.substring(z.indexOf("#PageNo=")+8,z.length):1,g.get(y+"/feeds/posts/summary/-/"+u+"?max-results=1&alt=json-in-script",f,"jsonp")))}var k,l,m,p,u,q={postperpage:Npage,numshowpage:3,previous:"&#171;",loadAjax:pajax,viewdefault:"list",container:".hfeed-inner",clist:"hlist",cgrid:"hgrip",next:"&#187;"},y=(q=g.extend({},q,a),window.location.protocol+
"//"+window.location.host),z=location.href.replace(rgx[17],"");b();var v=function(a){a=(l=a.feed.entry[0]).published.$t.substring(0,19)+l.published.$t.substring(23,29);a=encodeURIComponent(a);var f="page"==m?y+"/search?updated-max="+a+"&max-results="+q.postperpage+"#PageNo="+k:y+"/search/label/"+u+"?updated-max="+a+"&max-results="+q.postperpage+"#PageNo="+k;if(q.loadAjax){var p=rgx[14];g.get(f,function(){},"html").done(function(a){(a=g("<div></div>").append(a.replace(p,"")).find(q.container).children(".post-outer")).find(".index-post").each(function(){lpost(g(this))});
g(q.container).html(a);cdate();vmode({viewdefault:q.viewdefault,clist:q.clist,cgrid:q.cgrid});g(".blog-posts .loader").hide();a.addClass(rgx[31]);z=f;b();g("html, body").scrollTop(g("#main").offset().top-50);window.disqus_shortname&&g.getScript("https://"+window.disqus_shortname+".disqus.com/blogger_index.js")})}else location.href=f}}(jQuery)}function chside(a){a.parents(_$_[206]).length&&sSide&&(a=$(_$_[207]).height()+$(_$_[208]).height()+$(_$_[209]).height()+30,$(_$_[210]).css({height:a}))}
function thewid(a,g){var f=a.attr(_$_[211]),b=a.attr(_$_[212]),k=void 0!==a.attr(_$_[213])?a.attr(_$_[213]):_$_[1],l=void 0!==a.attr(_$_[214])?a.attr(_$_[214]):_$_[1],m=/slider/.test(b);var p=/gallery2/.test(b);/featured/.test(b);var u=/featured1/.test(b),q=/newsticker/.test(b),y=/carousel/.test(b),z=/timeline/.test(b),v=/(?=.*column2)(?=.*animated).*/.test(b),H=/(?=.*fbig1)(?=.*animated).*/.test(b);q?g.find(_$_[216]).prepend(_$_[215]):/(simple)/.test(b)?g.append(_$_[1]):-1===f.indexOf(_$_[217])&&
g.find(_$_[216]).wrapInner(_$_[223]+k+_$_[219]+(_$_[220]===f?_$_[1]:_$_[221]+f)+_$_[222]+Npage+_$_[224]).append(_$_[218]+k+_$_[219]+(_$_[220]===f?_$_[1]:_$_[221]+f)+_$_[222]+Npage+_$_[22]+mtx+_$_[77]);p=H?mx.fb1a:v?mx.cl2a:/(?=.*column1)(?=.*animated).*/.test(b)?mx.cl1a:/fbig1/.test(b)?mx.fb1:/fbig2/.test(b)?mx.fb2:/gallery1/.test(b)?mx.gl1:p?mx.gl2:m?mx.sl:/column1/.test(b)?mx.cl1:/column2/.test(b)?mx.cl2:/carousel1/.test(b)?mx.cr1:/carousel2/.test(b)?mx.cr2:/video/.test(b)?mx.vi:q?mx.nw:u?mx.fd1:
/featured4/.test(b)?mx.fd4:/list/.test(b)?mx.li:/gallery3/.test(b)?mx.gl3:z?mx.li:/featured2/.test(b)?mx.fd2:/featured3/.test(b)?mx.fd3:/hot/.test(b)?mx.ht:/ftpost/.test(b)?mx.feat:/rcpost/.test(b)?mx.rcpt:/rdpost/.test(b)?mx.rdpt:5;classname=m?_$_[225]+b:/column/.test(b)?_$_[226]+b:/fbig/.test(b)?_$_[227]+b:/gallery/.test(b)?_$_[228]+b:/featured/.test(b)?_$_[229]+b:y?_$_[230]+b:b;-1!=l.indexOf(_$_[231])&&g.children(_$_[216]).css({"background-color":l});g.addClass(classname.replace(/animated/,_$_[1])).append(y?
_$_[232]:_$_[1]);a.RCWid({blogURL:k,maxPosts:p,maxPostsPerTag:/(hot|featured1|ftpost)/.test(b)&&-1!==f.indexOf(_$_[217])?2:-1!==f.indexOf(_$_[217])?5:p,ShowTags:!!/(hot|featured|newsticker)/.test(b),tags:/(recent|random)/.test(f)?null:f.split(_$_[217]),postType:m?_$_[233]:y?_$_[234]:q?_$_[235]:/(featured1|featured2|featured3)/.test(b)?_$_[236]:/featured4/.test(b)?_$_[237]:_$_[1],ShowComment:!0,ShowImage:!0,auto:!!/autoplay/.test(b),review:!hrev,color:-1!=l.indexOf(_$_[231])?l:_$_[1],ShowPage:!!/pagenumber/.test(b),
hoverEffect:!!/(gallery|list|newsticker)/.test(b),random:_$_[238]===f,effect:!!/fade/.test(b)&&_$_[239],ShowDesc:!!/(featured|list|timeline|slider|newsticker|blogpost|halfpost|bigpost)/.test(b),wrapNum:/(featured1|featured4)/.test(b)?4:(/featured2/.test(b),5),summary:m||q||/(blogpost|halfpost|bigpost)/.test(b)?200:z?85:150,ShowAuthor:hauthor,fbig:!!/(fbig|column2|gallery1|gallery2|hot)/.test(b),animated:!!/animated/.test(b),startFirst:!(!v&&!H),slideSpeed:SSpeed});a.removeAttr(_$_[240])}
function discall(a,g,f){g.addClass(f);a.html(rgx[33]);postscribe(_$_[241],_$_[242]+dsqsn+_$_[243]+mx.dsq+_$_[244],{done:function(){var b=$(_$_[241]).html().replace(rgx[13],_$_[1]);a.html(b);$(_$_[247]).each(function(){$(this).find(_$_[246]).wrapAll(_$_[245])});$(_$_[241]).html(_$_[1])}})}
function flicall(a,g,f){g.addClass(f);a.html(rgx[33]);postscribe(_$_[248],_$_[249]+mx.fl+_$_[250]+dO+_$_[251],{done:function(){var b=$(_$_[248]).html().replace(rgx[14],_$_[1]);a.html(_$_[252]+b+_$_[94]);$(_$_[248]).html(_$_[1])}})}function crcom(a,g,f){a.html(rgx[33]);g.addClass(f);a.RCom()}
function fbsdk(){var a=document;var g=_$_[261];var f=_$_[262];var b=a.getElementsByTagName(g)[0];a.getElementById(f)||((a=a.createElement(g)).id=f,a.src=_$_[263]+fblang+_$_[264],b.parentNode.insertBefore(a,b));window.fbAsyncInit=function(){FB.init({appId:fbid,status:!0,xfbml:!0,cookie:!1,version:_$_[265]});FB.Event.subscribe(_$_[266],function(a){$.event.trigger({type:_$_[267],url:a})});FB.Event.subscribe(_$_[268],function(a){$.event.trigger({type:_$_[267],url:a})});FB.Event.subscribe(_$_[269],function(){chside($(_$_[270]));
$(_$_[270]).addClass(_$_[271])})}}function crfbox(a,g){a=a.replace(rgx[28],_$_[1]);g.addClass(_$_[272]);g.html(_$_[273]+a+_$_[274])}function ldwid(a,g,f,b){a.length?thewid(a,g):rgx[23].test(b)?discall(f,g,b):rgx[24].test(b)?flicall(f,g,b):rgx[25].test(b)?crcom(f,g,b):rgx[27].test(b)?crfbox(b,f):/complex/g.test(b)&&complx(b,g,f);g.addClass(_$_[275])}
function stickside(a,g,f){var b=a.children(_$_[296]),k=a.offset().top,l=a.height()-b.height()+k,m=b.height()+_$_[297],p=g;a.children(_$_[298]).length&&(k+=p=a.children(_$_[298]).outerHeight(!0)+15);f<k?b.removeClass(_$_[300]).css({position:_$_[299],top:p}):l<f?b.removeClass(_$_[300]).css({position:_$_[299],bottom:_$_[301],top:_$_[302]}):b.addClass(_$_[300]).css({top:g,height:m})}!1;
(function(a){a.fn.myTab=function(g){return g=jQuery.extend({active:1,showSpeed:400},g),this.each(function(){var f=a(this),b=f.children("[data-tab]"),k=g.active-1;f.addClass("simpleTab").prepend('<div class="tab-wrapper"></div>');b.addClass("tab-content").each(function(){a(this).hide();f.find(".tab-wrapper").append('<div><span class="btn">'+a(this).data("tab")+"</span></div>")}).eq(k).show();f.find(".tab-wrapper span").on("click",function(){var f=a(this).parent().index();return a(this).closest(".tab-wrapper").find(".activeTab").removeClass("activeTab"),
a(this).addClass("activeTab"),b.eq(f).is(":hidden")&&b.hide().eq(f).fadeIn(g.showSpeed),!1}).eq(k).addClass("activeTab")})}})(jQuery);(function(a){a.fn.hoverTimeout=function(g,f,b,k){return this.each(function(){var l=null,m=a(this);m.hover(function(){clearTimeout(l);l=setTimeout(function(){f.call(m)},g)},function(){clearTimeout(l);l=setTimeout(function(){k.call(m)},b)})})}})(jQuery);
(function(a){var g={customClass:"simply-scroll",frameRate:30,speed:1,orientation:"horizontal",auto:!0,autoMode:"loop",manualMode:"end",direction:"forwards",pauseOnHover:!0,pauseOnTouch:!0,pauseButton:!(a.fn.simplyScroll=function(f){return this.each(function(){new a.simplyScroll(this,f)})}),startOnLoad:!1};a.simplyScroll=function(f,b){var k=this;this.o=a.extend({},g,b||{});this.isAuto=!1!==this.o.auto&&null!==this.o.autoMode.match(/^loop$/);this.isRTL=(this.isHorizontal=null!==this.o.orientation.match(/^horizontal$/)&&
this.o.orientation==g.orientation)&&"rtl"==a("html").attr("dir");this.isForwards=!this.isAuto||this.isAuto&&null!==this.o.direction.match(/^forwards$/)&&this.o.direction==g.direction&&!this.isRTL;this.isLoop=this.isAuto&&"loop"==this.o.autoMode||!this.isAuto&&"loop"==this.o.manualMode;this.events=(this.supportsTouch="createTouch"in document)?{start:"touchstart MozTouchDown",move:"touchmove MozTouchMove",end:"touchend touchcancel MozTouchRelease"}:{start:"mouseenter",end:"mouseleave"};this.$list=a(f);
f=this.$list.children();if(this.$list.addClass("simply-scroll-list").wrap('<div class="simply-scroll-clip"></div>').parent().wrap('<div class="'+this.o.customClass+' simply-scroll-container"></div>'),this.isAuto?this.o.pauseButton&&(this.$list.parent().parent().prepend('<div class="simply-scroll-btn simply-scroll-btn-pause"></div>'),this.o.pauseOnHover=!1):this.$list.parent().parent().prepend('<div class="simply-scroll-forward"></div>').prepend('<div class="simply-scroll-back"></div>'),1<f.length){var l=
0;(this.isHorizontal?(f.each(function(){l+=a(this).outerWidth(!0)}),f.eq(0).outerWidth(!0)*f.length!==l):(f.each(function(){l+=a(this).outerHeight(!0)}),f.eq(0).outerHeight(!0)*f.length!==l))&&(this.$list=this.$list.wrap("<div></div>").parent().addClass("simply-scroll-list"),this.isHorizontal?this.$list.children().css({"float":"left",width:l+"px"}):this.$list.children().css({height:l+"px"}))}this.o.startOnLoad?a(void 0).load(function(){k.init()}):this.init()};a.simplyScroll.fn=a.simplyScroll.prototype=
{};a.simplyScroll.fn.extend=a.simplyScroll.extend=a.extend;a.simplyScroll.fn.extend({init:function(){this.$items=this.$list.children();this.$clip=this.$list.parent();this.$container=this.$clip.parent();this.$btnForward=a(".simply-scroll-forward",this.$container);this.isHorizontal?(this.itemMax=this.$items.eq(0).outerWidth(!0),this.clipMax=this.$clip.width(),this.dimension="width",this.moveBackClass="simply-scroll-btn-left",this.moveForwardClass="simply-scroll-btn-right",this.scrollPos="Left"):(this.itemMax=
this.$items.eq(0).outerHeight(!0),this.clipMax=this.$clip.height(),this.dimension="height",this.moveBackClass="simply-scroll-btn-up",this.moveForwardClass="simply-scroll-btn-down",this.scrollPos="Top");this.posMin=0;this.posMax=this.$items.length*this.itemMax;var f=Math.ceil(this.clipMax/this.itemMax);if(this.isAuto&&"loop"==this.o.autoMode&&(this.$list.css(this.dimension,this.posMax+this.itemMax*f+"px"),this.posMax+=this.clipMax-this.o.speed,this.isForwards?(this.$items.slice(0,f).clone(!0).appendTo(this.$list),
this.resetPosition=0):(this.$items.slice(-f).clone(!0).prependTo(this.$list),this.resetPosition=this.$items.length*this.itemMax,this.isRTL&&(this.$clip[0].dir="ltr",this.$items.css("float","none")))),this.resetPos(),this.interval=null,this.intervalDelay=Math.floor(1E3/this.o.frameRate),this.isAuto||"end"!=this.o.manualMode)for(;0!=this.itemMax%this.o.speed;)if(0==--this.o.speed){this.o.speed=1;break}(c=this).trigger=null;this.funcMoveForward=function(a){void 0!==a&&a.preventDefault();c.trigger=c.isAuto||
"end"!=c.o.manualMode?null:this;c.isAuto?c.isForwards?c.moveForward():c.moveBack():c.moveForward()};this.funcMovePause=function(){c.movePause()};this.funcMoveStop=function(){c.moveStop()};this.funcMoveResume=function(){c.moveResume()};this.isAuto&&(this.paused=!1,this.supportsTouch&&this.$items.find("a").length&&(this.supportsTouch=!1),this.o.pauseOnHover&&!this.supportsTouch&&this.$clip.bind(this.events.start,this.funcMovePause).bind(this.events.end,this.funcMoveResume),this.funcMoveForward())},
moveForward:function(){var a=this;this.movement="forward";null!==this.trigger&&this.$btnBack.removeClass("disabled");a.interval=setInterval(function(){a.$clip[0]["scroll"+a.scrollPos]<a.posMax-a.clipMax?a.$clip[0]["scroll"+a.scrollPos]+=a.o.speed:a.isLoop?a.resetPos():a.moveStop(a.movement)},a.intervalDelay)},movePause:function(){clearInterval(this.interval)},moveStop:function(f){this.movePause();null!==this.trigger&&(void 0!==f&&a(this.trigger).addClass("disabled"),this.trigger=null);this.isAuto&&
"bounce"==this.o.autoMode&&("forward"==f?this.moveBack():this.moveForward())},moveResume:function(){"forward"==this.movement?this.moveForward():this.moveBack()},resetPos:function(){this.$clip[0]["scroll"+this.scrollPos]=this.resetPosition}})})(jQuery);
var _$_=["cookie","",";expires=",";path=/","=","test","ok",";","","click","",'<input class="emoKey" type="hidden" size="','" value=" ','" />',"select","cursor","pointer","","active","","",'<ul class="hide ','">',"i",'<i class="',"class",'"></i>',"href","a","_","-",'<a href="',"</a>",'</ul><a href="','</a><ul class="hide ',"li","</ul>","ul",".summary-content","file-text-o",".noimage",".thumb-img",".post-type",".thumb-area","title",".jmptext",".h2","s400","s300","data-img","s72-c","/default.jpg","/mqdefault.jpg",
"https://img.youtube.com/vi/","video-camera","/","no_image","rgba(0, 0, 0, 0.15)","img.youtube.com",'<span class="youtubeplay"><i class="fa fa-play-circle-o"></i></span>',"hyoutube",".latest-img","music","camera-retro","quote-left",'<i class="fa fa-',"$1",'<div class="review-place ','"><span class="review-value">','</span><div class="slice"><div class="bar"></div></div></div>',"width","%",".bar","&quot;",'...<a href="','" class="rmtext" title="'," ","</a>","style","background:","https",'url("','")',
" no-repeat center center;background-size: cover","","","","#ajax-search-form",":text",'<div class="src-result ',' hide" id="search-result"></div>',"#search-result","submit",'<div class="loader">',"</div>","//","/feeds/posts/default?alt=json-in-script&q=","&max-results=",'<div class="src-header">'," &quot;","&quot;</div>",'<a class="src-close ','" href="/">&times;</a><div class="src-area">',"ig","<span class='src-mark'>","</span>","alternate","enclosure","content","summary","media$thumbnail","/s",
"-c/","default","mqdefault","...",'<div class="src-item"><div class="src-img-outer ',' go-left"><a class="src-img show" " ',"url('","')",' no-repeat center center;background-size: cover" href="','" ><div class="post-type absolute"><i class="fa fa- ','"></i></div></a></div><a class="',' src-title" href="#','<p class="src-summary" >',"</p>",'<div class="src-morepost"><a class="show btn" title="more" href="/search?q=',"&quot;</a></div>",'<a class="close" href="/">&times;</a><strong>',"</strong>","jsonp",
".src-close","grid","vlist","vgrip",".post-outer",".blog-posts.hfeed","#view .grid","#view .list","list","<b>","</b><div><span>","</span><small>","</small></div>",".postdate",".index-post",".published","div","<div></div>","a.blog-pager-older-link","","https://",".disqus.com/blogger_index.js","html",".hfeed-inner","vgrid","item",'<a class="loadpost show" href="javascript:;">','<div class="loader hide"></div>','<div class="rct-loadmore no-decor" ></div>',".blog-pagerindex","\u00ab","hlist","hgrip",
"&#187;","page",'<span class="showpage"><a href="">',"</a></span>",'<span class="showpageNum"><a rel="noindex" href="/search/label/',"?&max-results=",'<span class="showpageNum"><a class="xpagex" href="#" alt="','<span class="showpageNum"><a class="xlabelx" href="#" alt="','<span class="showpageNum"><a href="">1</a></span>','">1</a></span>','<span class="dotxpage"> ... </span>','<span class="showpagePoint">','<span class="showpageNum"><a href="#" class="xpagex" alt="','<span class="showpageNum"><a rel="noindex" href="#" class="xlabelx" alt="',
"pageArea","blog-pagerindex","display","block","load-next",".hfeed .loader","alt","/feeds/posts/summary?start-index=","&max-results=1&alt=json-in-script","/feeds/posts/summary/-/","?start-index=",".blog-pagerindex a.xpagex, .blog-pagerindex a.xlabelx","/search/label/","?updated-max","?max","?&max","?q=",".html","max-results=","#PageNo=","/feeds/posts/summary?max-results=1&alt=json-in-script","label","?max-results=1&alt=json-in-script","/search?updated-max=","?updated-max=",".blog-posts .loader","#main",
"html, body",".sidebar-right","#sidebar-top","#sidebartabs","#sidebar-bottom",".sidebar-right .wrap-inner","data-label","data-type","data-url","data-color"," ","h2",",",'<a class="morepost btn" href="',"/search","recent","/label/","?max-results=",'<a href="','"></a>',"slider ","column ","fbig ","gallery ","featured ","carousel ","#",'<div class="owl-controls"><div class="owl-nav"></div></div>',"s","c","n","fs","f3","random","fade","data-label data-url data-type data-color","#drcmt",'<script async="async" src="https://',
".disqus.com/recent_comments_widget.js?num_items=",'&avatar_size=32&excerpt_length=100&hide_mods=0" >\x3c/script>','<div class="disqus-summary" />',".dsq-widget-user,.dsq-widget-comment,.dsq-widget-meta",".dsq-widget-item","","","","","","{","}",'<div class="recent-tab">','<div data-tab="',"aazs-widget",".recent-tab","complex ",".tab-content","script","facebook-jssdk","https://connect.facebook.net/","/sdk.js","v5.0","edge.create","unlock_content","message.send","xfbml.render",".FBbox","load-done",
"FBbox",'<div id="FBbox"><div class="fb-page" data-href="','" data-width="550"></div></div>',"widget-loaded","dhref-done","","/w400/","","","","","","","","","","","","","",'<span class="hide">Facebook</span>',"","",".dhref",".wrap-inner","px",".innerwrap","absolute","side-fixed","0","auto","sub-menu","sub-sub-menu",".submenu","thumb-outer","animated zoomIn","heading-text",'<div class="loader"></div>',".varsumlength",".varfixMenu",".varmonthName","Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec",
".varstickySide",".varsliderspeed",".varnavipostpage",".varmaxcommentdepth",".vardateformat","YYYY/MM/DD",".varrcadminBlog","y",".varhideauthor",".varhideLatest",".varcseID",".varhideEmo",".varhomelist",".varfeatpost",".varhomePageNavi",".varfbappsid","160447341157187",".varfblang","en_US",".vardajaxPageNavi",".varsrctext","Type and hit enter to search...",".varntext","Previous Article",".varptext","Next Article",".varmtext","",".varlmtext","",".varvmtext","",".varreltext","RELATED CONTENT",".varrectext",
"Recent Post",".varrecotext","Recommended For You",".vartwitterauthor","A_A_Z_S",".vardisqusshortname","",".varshowrelated",".varshowrecommended",".varrelstyle","carousel",".varhexcerpt",".varhreview",".vartopbreakline",".varbottombreakline",".varautoplay",".vartopbreaklineload",".varbottombreaklineload","",".varrecentpost",".varrandompost",".varfeaturedpost",".varrecentcomment",".varfbig1",".varfbig2",".varfbig1animated",".vargallery1",".vargallery2",".vargallery3",".varcolumn1",".varcolumn2",".varcolumn1animated",
".varcolumn2animated",".varnewsticker",".varslider",".varcarousel1",".varcarousel2",".varrelated",".varvideo",".varfeatured1",".varfeatured2",".varfeatured3",".varfeatured4",".varlist",".varhot",".vardisquscomment","",".vartimeline","allaboutzodiacsigns","",".home-area #Blog1,.home-area .posts-title","",".item-topmeta",".post-body",'if (this.value==""){this.value="','";}','if (this.value=="','"){this.value="";}',".errorsrc input,.search-form input","text/javascript","https","https:","https:","//www.google.com/cse/cse.js?cx=",
"","#body-area","custom-cse-aazs","searchresults-only0",".comments-tabs",".canUrl",".bposId",".pstUrl","<div data-tab='Google'><div class='tab-blogger'></div></div>","<div data-tab='Disqus'><div class='tab-disqus' id='disqus_thread'></div></div>","<div data-tab='Facebook'><div class='tab-facebook'><div class='fb-comments' data-numposts='5' data-width='100%' data-href='","'></div></div></div>","","show",".menu",".",'<div class="sub-icon"><span class="sub-button ',' btn"><i class="fa fa-caret-down"></i></span></div>',
"submenu","ul.",' btn"><i class="fa fa-caret-right"></i></span></div>',"subsubmenu","<span class='menu-desc'>",".menu li a","<span class='soc-desc'>","<span class='soc-count'>",".social-desc","have-desc",".menu-desc",".main-menu li",".sc-move","padding-left",".main-menu a","a.home-icon","left",'.main-menu a[href="#"]',"easeOutQuad","nohover",".home-icon",".main-menu > li",":not(:animated)","easeInExpo",".menu li","","","",'<div class="emoWrap hide">',"","iframe#comment-editor"," <amp-img width='36' height='36' layout='responsive' '' src='",
"' alt='","'/>","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","data-tab",".widget","#sidebar-tabs1",".labels-wrap",".plabelsbtn",".comments","home-area","#container","index-area","index","#aazs",".searchQuered","archive","ablist","abgrip","<div ",".HTML",'"','" ',"f2","slide-width=630",' class="widget-area mywidget hide"></div><div class="handle mywidget hide"></div>','<div class="wid-pagenumber"></div>','<a class="wid-pagenum btn" alt="1">\u00ab</a>',
'<a class="wid-pagenum btn" alt="','">\u00ab</a>','<a class="wid-pagenum btn" alt="1">1</a>',"<span> ... </span>","<span ",";border-color:",';background-image:initial" ','class="actual">','">&#187;</a>',".wid-pagenumber",'<div class="handle"></div><div class="handle2 json-process"><div class="loader"></div></div>',".widget-area",".handle2","data-tag","/feeds/posts/default?start-index=","&orderby=published&alt=json-in-script","/feeds/posts/default/-/",".wid-pagenum","replies","text/html",'class="review-place absolute"><span class="review-value">',
'</span><div class="slice"><div "width:','%" class="bar"></div></div></div>',".blogspot","com",".blogspot.com",".blog-posts",".items:gt(",")",".handle","hide",".handle,.loader,.handle2",".readmorebut","noborder","aazs","owl-carousel","fadeOut","zoomIn",".owl-nav",".items","<div class='wrapitem'></div>","<div class='feat-wrapitem'></div>",'<div class="feat-wrapinner"></div>',".feat-wrapitem:first-child",".feat-wrapinner","<div class='fbig-widget-area'></div>","gallery"," hovergallery","show botwid",
".hover-info",".hoveffect",".thumb-outer",".rcthumb","s150","s600","mega-menu","feed-proc","zoomIn animated",".fbig-widget-area .items","<div class='animated-item'></div>",".animated-item",'<div class="animated-area"></div>',"mouseleave touchend","start","mouseenter touchstart","stop",".owl-carousel","score","d",' class="',"first-item ",'items"><div class="items-inner">','class="rcptime">','class="postdate absolute"><b>',"</small></div></div>",'<div class="table-cell thumb-outer'," hoveffect",'"><div class="mythumb thumb-area',
" first-image",'"><div class="post-type absolute"><i class="fa fa-','"></i></div><a class="rcthumb show" title="','" href="','" data-img="','"',"ytimg.googleusercontent.com","</a></div></div>",'"border-',"right","-color:",'class="',"first-area ",'content-area table-cell">','"color:','class="ct-before"><i class="fa fa-circle"></i></div>',"<p ",'"',"background-","color:",'class="heading-text"><a ','class="hoveffect"',' href="','</a></p><div class="metainfo">','<div class="hide">',"</div> ",'<span class="wid-date"><i class="fa fa-calendar"></i> ',
"DD","MM","YYYY",'<span class="widcomments"><i class="fa fa-comments-o"></i> <a href="','"></a>','<div class="psummary hide">','<a class="readmorebut" href="','#more" title="','">More</a>','<span class="rcptags absolute"><a ','class="btn" title="',"</div></div>",'a[class="item-tag"]:lt(','<h2><span class="title-wrap">','</span></h2><div class="owl-nav"></div>',"/feeds/posts/summary?max-results=0&orderby=published&alt=json-in-script","/feeds/posts/default?max-results=","&orderby=published&start-index=",
"&alt=json-in-script","/feeds/comments/default?alt=json-in-script&orderby=published",'<div class="rcomment-area">','<div class="rcomment-item'," rcadmin"," rcguest",'<amp-img class="rcomment-img" alt="','" title="','" href="','" src="','"/>','<div class="rcomment-info"><a href="#','</a><a class="rcomment-title" href=" ','</a><div class="rcomment-meta"><div class="com-date"><b>','</small></div></div><div class="com-time">',"</div></div></div>",'<div class="rcomment-summary">','<div class="clear"></div></div>',
" <amp-img layout='responsive' alt='emo' src='","' class='emo' alt='",".rcomment-summary","<span></span>","Anonymous","","g",'<div class="shrt shrt-$1" $2 $3>',".post-body,.cm_body p,.HTML .widget-content","icon",'<i class="fa shrt-icon ',"fa-","Tab","Dont Have any text content",".shrt-content","shrt-tabhtml",".shrt-tab,.shrt-vtab","","","",'<div class="acrd-content">',"My accordion",".shrt-item","current",".acrd-toggle","showed",".acrd-content",".shrt-accordion","fast",".acrd-content:visible","h3.acrd-toggle",
".shrt-accordion .acrd-toggle","src","color","featured","height","visual","comments","user","playlist",'<div class="inlinestyle frame-shrt-soundcloud'," pfeatured",'"><amp-iframe width="',"320",'" height="',"130",'" layout="responsive" resizable="resizable" sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-top-navigation" scrolling="no" src="https://w.soundcloud.com/player/?url=https://api.soundcloud.com/',"tracks","users","xxxxxxx","&amp;color=","ff5500","&amp;auto_play=","false",
"&amp;hide_related=false&amp;show_comments=","&amp;show_user=","true","&amp;show_reposts=false&amp;visual=",'"><div overflow="true"/></amp-iframe></div>',".shrt-soundcloud","highlight","background","info","logo",'<div class="inlinestyle frame-shrt-dailymotion','"><amp-iframe width="',"270",'" layout="responsive" resizable="resizable" sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-top-navigation" src="https://www.dailymotion.com/embed/video/',"x12k542","?logo=","1","&info=",
"&highlight=","29b7ff","&foreground=","ffffff","&background=","000000",'" allowfullscreen><div overflow="true"/></amp-iframe></div>',".shrt-dailymotion","control","related",'<div class="inlinestyle frame-shrt-youtube',"370",'" layout="responsive" resizable="resizable" sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-top-navigation" src="https://www.youtube.com/embed/',"9ua_4ajpP58","?list=","&amp;rel=","&amp;controls=","&amp;showinfo=",'" allowfullscreen><div overflow="true"/></amp-iframe></div>',
".shrt-youtube",'<div class="inlinestyle frame-shrt-map','" src="https://www.google.com/maps/embed?pb=','"></amp-iframe></div>',".shrt-map","shrt-message",".shrt-alert, .shrt-warning, .shrt-update, .shrt-success, .shrt-info, .shrt-error",'<div class="headline">','<div class="message-wrapper">',".shrt-message","url","rel",'href="','"','<a class="shrtImgUrl ',' rel="','<amp-img layout="responsive" class="shrtImg','" width="',"",'"/>',".shrt-img","glpost","br",".shrt-pgallery,.shrt-bgallery","type",
'<pre data-codetype="',"HTML","Add some code here","</pre>",".shrt-code","pre",'<span class="line-number"></span>','<span class="cl"></span>',"span","<span>","#contact",".shrt-contact",'" class="jdshrt-tooltip">',"Insert Link Title","Insert Tooltip Text","</span></a>",".shrt-tooltip",'<div class="shrt-slide-item"><div class="shrt-inner"><a class="shrt-owl-img" "background: url(',') no-repeat center center;background-size: cover;" href="','"></a><div class="shrt-summary">','<h3><a href="',"</a></h3>",
"<p>","shrt-inhtml",".shrt-pslide",'<div class="shrt-carousel-item"><div class="shrt-inner"><a class="shrt-owl-img" "background: url(',".shrt-pcarousel","top","review-value",'<div class="rev-item"><div class="rev-desc">',"",'</span></div><div class="rev-value-outer"><div class="rev-value" data-value="','" "width:','%"></div></div></div>','<div class="rev-summary"><div class="rev-desc-place table-cell"><h4>',"","</h4><span>","",'</span></div><div class="rev-overall table-cell"><div class="overall-inner"><div class="c100"><div class="rev-score"></div><div class="slice"><div class="fill"></div><div class="bar"></div></div></div><span>',
"","</span></div></div></div>",'<div class="top-revscrore"><div class="c100"><div class="rev-score"></div><div class="slice"><div class="fill"></div><div class="bar"></div></div></div><span>',"</span></div>",".rev-value","data-value",".rev-score","p",".c100","rotate(","deg)",".c100 .bar",".shrt-review",".widget-content",'data-url="','data-color="','<div class="aazs-widget" data-label="','" data-type="',">",'<div class="aazs-widget" data-label="random" data-type="simple rcpost">','<div class="aazs-widget" data-label="random" data-type="simple rdpost">',
'" data-type="simple ftpost">',".aazs-widget",".post-body strike",".post-title",".post-body h2 strike",".post-body h3 strike",".post-subtitle","id",".post","#post-url","unlocked","unlocked-","</locktag>","<locktag>",'<div class="locked-content"><div class="inner"><i class="color fa fa-lock"></i><div class="locked-content-actions"><div class="locked-content-action"><div class="fb-like" data-href="','" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div></div></div></div></div>',
"",".item-post .post-body","","","","","","",".item-area",".cm_form",'<a href="#origin_cform" onclick="Reset_Comment_Form()">',"#r_f_c","#comment-editor","&parentID=","#%7B",".profile-sec .widget",' hover" href="','<a class="fa fa-',".fa","<div class='authoriconBox'></div>",".profile-sec .widget-content",".item-topmeta .fn","All About Zodiac Signs",".authoriconBox",".authorProfile p",".authorSocial",'<span class="'," hover","fa fa-",'"></span>',".authorSocial a",".adsinside","left-post","body","right-post",
"left-side","right-side","full-post","hide-adstitle",'<div class="adsinside-it ads-outer"></div>',".adsinside-it",".adsbelow",'<div class="adstitle',"",'"><div class="adspltop"></div>',"",".adspltop","","","","",".adsendpost",'<div class="adsbottom',"",'<div class="adsplbottom"></div></div>',".bottom-infoitem",".adsplbottom","",'<input type="hidden" class="aazs-page"></input><input type="hidden" class="aazs-per-page"></input>','<div class="page-place no-decor"></div>',"[lnt]","[fnt]",'</div><div class="page-item">',
'<div class="page-item">',".page-place",".aazs-page",".aazs-per-page",'<a class="previous_link btn"><i class="fa fa-chevron-left"></i></a>','<a class="page_link btn" data-title="','" ","href"," longdesc="','<a class="next_link btn"><i class="fa fa-chevron-right"></i></a>',"active_page",".page_link:first","none",".active_page",".page_link[longdesc=","]",".page_link",".previous_link",".next_link","data-title",".all_link",'@<a href="#c',".cm_wrap .cm_body p","#comment-form_","#rc","parentId","data-level",
"#c",":first",":first .cm_reply",'<div class="cm_wrap" id="c','" data-level="'," .cm_child:first","/s55-c/",".cm-img",'<div class="nw_com"></div>',".nw_com",".comments-tabs .tab-wrapper div",".comments-tabs .tab-wrapper","table","pfeatured",".tr-caption",'<span class="pcaption absolute">',".pfeatured",".post-body img",".post-featured",'<div class="slide-pfeatured"></div>',".slide-pfeatured",".glpost",".separator",".post-featured a",".post-featured > a",".post-featured img","/s600/",'<div class="hide url-post"><input aria-label="Post Url" class="url-post-input" type="text" value="" ',
'" /></div>',".url-post",".showlink","hover",".item-share a",".item-snippet",".body-area","","show-popup","","","","","","",'<a rel="noindex" class="menu-morepost'," random",'" href="/search','"></a>',"mcarousel",'<div class="normal-tab">',".normal-tab",'<a rel="noindex" class="menu-morepost" href="/search/label/',"mtab","mbig","menulinks",".links-submenu .widget",".links-submenu",'<div class="links-content"><h2>','</h2><div class="widget-content">',".links-content","gridpost",'<a rel="noindex" class="grid-h2" href="/search',
'<a rel="noindex" class="morepost btn" href="/search',"li.submenu",".menu-search",".mobile-search",".social-icon",".mobile-icons",":hidden",".mobile-menu .sub-icon",'<a class="blog-pager-older-link-item go-right oldernewerright" title="Next Article - [title] - posted on [date]" href="[url]"><span>',"</span><div>[title]</div></a>",'<a class="blog-pager-newer-link-item go-left oldernewerleft" title="Previous Article - [title] - posted on [date]" href="[url]"><span>','<amp-img layout="responsive" alt="blog-pager" src="',
"a.blog-pager-older-link-item","a.blog-pager-newer-link-item","data-trans","#body-area *","span.trans","scroll",".header-wrap","scrolled",".container","scroll-up","fixmenu-work",".allaboutzodiacsigns","0px",".sidebar-left","stickyside-work",".widget-loaded","#facebook-jssdk","item-area",".tab-disqus","disqus-loaded",".disqus.com/embed.js","data-timestamp","","","","",":","a.icons-facebook","a.dhref-done","item-page-loaded",".pager-isi","/feeds/posts/default?alt=json-in-script&published-min=","&max-results=0&callback=?",
"/feeds/posts/default?alt=json-in-script&start-index=","&max-results=3&callback=?","/feeds/posts/default?alt=json-in-script&start-index=2&max-results=1&callback=?",".populars-img",".img-change",'background:url("','") no-repeat center center;background-size: cover',"img-change","showup",".gotop",".item-tag",".reco-place",'<div class="reco-place blog-posts"><h4>','</h4><div class="reco-inner"></div><span class="btn reco-close"><svg height="28" viewBox="0 3 24 24" width="28"><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z" fill="#fff"></path></svg></span></div>',
".reco-inner","showIt","reco-click",".reco-close",".itemtags",".footer-area","related-work","#related_posts","related-work rel-","fbig","data-count","data-number",".tagscount","[id=","string","transitioning","1s ease-in-out","a[href*=\\#]:not([href=\\#])","transitionend webkitTransitionEnd msTransitionEnd oTransitionEnd","resize","small-wid",".HTML > .widget-content","small-post",".tab-blogger #blogger_cm","#blogger_cm",".tab-blogger","#Blog1","#gPlusComment > div",".main-wrapper",".sidebar-right .innerwrap",
".sidebartabs","min-height","-webkit-transform","-o-transform","-ms-transform","-moz-transform","transform","translate3d(1px,1px,1px)","","","ontouchstart","touch","Safari","CriOS","standalone"," translateZ(0)","onorientationchange","orientationchange","click touchstart","mousedown","touchmove","mousemove","touchend","mouseup","0s",".mobile-menu .tab-wrapper a,.sub-button,.sub-button .fa","ms","translate(","px,0)","","","#allaboutzodiacsigns","",".index-post-outer"],rgx=[/\s|&nbsp;/g,_$_[299],_$_[303],
_$_[304],_$_[305],/(<|\[)amp-img +(.*?)src=(['"])([^'"]+?)(['"])(.*?) *\/?(>|\])/i,/(youtu.be\/|youtube.com\/(watch\?(.*&)?v=|(embed|v)\/))([^\?&"'>]+)/i,/\/s\d+(\-c)?\//i,/\[youtube +(.*?)src=(['"])([^'"]+?)(['"])(.*?) *\/?\]/i,/vimeo.com\/|dailymotion.com\/|youtube.com\/|youtu.be\/|\[dailymotion|\[youtube/i,/soundcloud.com\/|\[soundcloud/i,/\[gallery\]|\[pgallery|\[bgallery/i,/<blockquote>/i,/<(?:script|style)\b[^<]*(?:(?!<\/(?:script|style)>)<[^<]*)*<\/(?:script|style)>/gi,/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
/<\S[^>]*>/g,/\[\S[^\]]*\]/g,/(:?\?|&)m=(1|0)/g,/[^[\]]+(?=])/g,/recentpost/g,/randompost/g,/featuredpost/g,/featuredpost\//g,/disquscomment/g,/pn/g,/recentcomment/g,/pL/g,/FBbox/g,/FBbox\//g,/\[item *review-fe=("[^"]+") *\]/g,_$_[306],_$_[307],_$_[308],_$_[309],/(tooltip|dailymotion|youtube|soundcloud|code|accordion|content|item|alert|success|warning|update|error|info|tab|vtab|pgallery|bgallery|amp-img|contact|2column|3column|4column|pslide|pcarousel|map|review)/],sumLength=$(_$_[310]).length?$(_$_[310]).attr(_$_[44]):
200,fixM=!$(_$_[311]).length||_$_[235]!=$(_$_[311]).attr(_$_[44]),mName=$(_$_[312]).length?$(_$_[312]).attr(_$_[44]).split(_$_[217]):_$_[313].split(_$_[76]),sSide=!$(_$_[314]).length||_$_[235]!=$(_$_[314]).attr(_$_[44]),SSpeed=$(_$_[315]).length?$(_$_[315]).attr(_$_[44]):5E3,Npage=$(_$_[316]).length?$(_$_[316]).attr(_$_[44]):10,fC=$(_$_[317]).length?$(_$_[317]).attr(_$_[44]):2,dformat=$(_$_[318]).length&&_$_[235]!=$(_$_[318]).attr(_$_[44])?$(_$_[318]).attr(_$_[44]):_$_[319],admBlog=!$(_$_[320]).length||
_$_[321]!=$(_$_[320]).attr(_$_[44]),hauthor=!$(_$_[322]).length||_$_[321]!=$(_$_[322]).attr(_$_[44]),hLast=!(!$(_$_[323]).length||_$_[321]!=$(_$_[323]).attr(_$_[44])),gCSE=!(!$(_$_[324]).length||_$_[235]==$(_$_[324]).attr(_$_[44])),cseID=$(_$_[324]).length&&_$_[235]!=$(_$_[324]).attr(_$_[44])?$(_$_[324]).attr(_$_[44]):_$_[1],hlist=!(!$(_$_[326]).length||_$_[321]!=$(_$_[326]).attr(_$_[44])),fpost=!$(_$_[327]).length||_$_[235]!=$(_$_[327]).attr(_$_[44]),hpagenav=!$(_$_[328]).length||_$_[235]!=$(_$_[328]).attr(_$_[44]),
fbid=$(_$_[329]).length?$(_$_[329]).attr(_$_[44]):_$_[330],fblang=$(_$_[331]).length?$(_$_[331]).attr(_$_[44]):_$_[332],pajax=!$(_$_[333]).length||_$_[321]!=$(_$_[333]).attr(_$_[44]),stx=$(_$_[334]).length&&_$_[235]!=$(_$_[334]).attr(_$_[44])?$(_$_[334]).attr(_$_[44]):_$_[335],ntx=$(_$_[336]).length&&_$_[235]!=$(_$_[336]).attr(_$_[44])?$(_$_[336]).attr(_$_[44]):_$_[337],ptx=$(_$_[338]).length&&_$_[235]!=$(_$_[338]).attr(_$_[44])?$(_$_[338]).attr(_$_[44]):_$_[339],mtx=$(_$_[340]).length&&_$_[235]!=
$(_$_[340]).attr(_$_[44])?$(_$_[340]).attr(_$_[44]):_$_[341],lmtx=$(_$_[342]).length&&_$_[235]!=$(_$_[342]).attr(_$_[44])?$(_$_[342]).attr(_$_[44]):_$_[343],vmtx=$(_$_[344]).length&&_$_[235]!=$(_$_[344]).attr(_$_[44])?$(_$_[344]).attr(_$_[44]):_$_[345],reltx=$(_$_[346]).length&&_$_[235]!=$(_$_[346]).attr(_$_[44])?$(_$_[346]).attr(_$_[44]):_$_[347],rectx=$(_$_[348]).length&&_$_[235]!=$(_$_[348]).attr(_$_[44])?$(_$_[348]).attr(_$_[44]):_$_[349],recotx=$(_$_[350]).length&&_$_[235]!=$(_$_[350]).attr(_$_[44])?
$(_$_[350]).attr(_$_[44]):_$_[351],twau=$(_$_[352]).length&&_$_[235]!=$(_$_[352]).attr(_$_[44])?$(_$_[352]).attr(_$_[44]):_$_[353],dsqsn=$(_$_[354]).length&&_$_[235]!=$(_$_[354]).attr(_$_[44])?$(_$_[354]).attr(_$_[44]):_$_[1],dO=$(_$_[355]).length&&_$_[235]!=$(_$_[355]).attr(_$_[44])?$(_$_[355]).attr(_$_[44]):_$_[1],shrel=!$(_$_[356]).length||_$_[235]!=$(_$_[356]).attr(_$_[44]),shreco=!(!$(_$_[357]).length||_$_[321]!=$(_$_[357]).attr(_$_[44])),relst=$(_$_[358]).length?$(_$_[358]).attr(_$_[44]):_$_[359],
hecpt=!(!$(_$_[360]).length||_$_[321]!=$(_$_[360]).attr(_$_[44])),hrev=!(!$(_$_[361]).length||_$_[321]!=$(_$_[361]).attr(_$_[44])),tbline=!(!$(_$_[362]).length||_$_[321]!=$(_$_[362]).attr(_$_[44])),bbline=!(!$(_$_[363]).length||_$_[321]!=$(_$_[363]).attr(_$_[44])),aplay=!(!$(_$_[364]).length||_$_[321]!=$(_$_[364]).attr(_$_[44])),blinest=$(_$_[365]).length?$(_$_[365]).attr(_$_[44]):_$_[220],btlinest=$(_$_[366]).length?$(_$_[366]).attr(_$_[44]):_$_[220],dajaxsrc=!(!$(_$_[367]).length||_$_[321]!=$(_$_[367]).attr(_$_[44])),
mx={rcpt:$(_$_[368]).length?$(_$_[368]).attr(_$_[44]):4,rdpt:$(_$_[369]).length?$(_$_[369]).attr(_$_[44]):4,feat:$(_$_[370]).length?$(_$_[370]).attr(_$_[44]):4,com:$(_$_[371]).length?$(_$_[371]).attr(_$_[44]):5,fb1:$(_$_[372]).length?$(_$_[372]).attr(_$_[44]):5,fb2:$(_$_[373]).length?$(_$_[373]).attr(_$_[44]):5,fb1a:$(_$_[374]).length?$(_$_[374]).attr(_$_[44]):8,gl1:$(_$_[375]).length?$(_$_[375]).attr(_$_[44]):10,gl2:$(_$_[376]).length?$(_$_[376]).attr(_$_[44]):7,gl3:$(_$_[377]).length?$(_$_[377]).attr(_$_[44]):
6,cl1:$(_$_[378]).length?$(_$_[378]).attr(_$_[44]):5,cl2:$(_$_[379]).length?$(_$_[379]).attr(_$_[44]):5,cl1a:$(_$_[380]).length?$(_$_[380]).attr(_$_[44]):9,cl2a:$(_$_[381]).length?$(_$_[381]).attr(_$_[44]):8,nw:$(_$_[382]).length?$(_$_[382]).attr(_$_[44]):9,sl:$(_$_[383]).length?$(_$_[383]).attr(_$_[44]):5,cr1:$(_$_[384]).length?$(_$_[384]).attr(_$_[44]):9,cr2:$(_$_[385]).length?$(_$_[385]).attr(_$_[44]):9,rl:$(_$_[386]).length?$(_$_[386]).attr(_$_[44]):9,vi:$(_$_[387]).length?$(_$_[387]).attr(_$_[44]):
6,fd1:$(_$_[388]).length?$(_$_[388]).attr(_$_[44]):8,fd2:$(_$_[389]).length?$(_$_[389]).attr(_$_[44]):10,fd3:$(_$_[390]).length?$(_$_[390]).attr(_$_[44]):10,fd4:$(_$_[391]).length?$(_$_[391]).attr(_$_[44]):7,lt:$(_$_[392]).length?$(_$_[392]).attr(_$_[44]):6,ht:$(_$_[393]).length?$(_$_[393]).attr(_$_[44]):4,dsq:$(_$_[394]).length?$(_$_[394]).attr(_$_[44]):4,fl:$(_$_[395]).length?$(_$_[395]).attr(_$_[44]):8,li:$(_$_[396]).length?$(_$_[396]).attr(_$_[44]):5};
navigator.userAgent.match(/Android|iPhone/i)&&!navigator.userAgent.match(/iPod|iPad/i)&&(document.getElementById(_$_[397]).className=document.getElementById(_$_[397]).className+_$_[398]);hLast&&$(_$_[399]).hide();hecpt&&$(_$_[400]).hide();$(_$_[402]).before($(_$_[401]));$(_$_[407]).attr({onblur:_$_[403]+stx+_$_[404],onfocus:_$_[405]+stx+_$_[406],fe:stx});
var csystext=$(_$_[417]).text(),cnurl=$(_$_[418]).attr(_$_[44]),bpstid=$(_$_[419]).attr(_$_[44]),psturl=$(_$_[420]).attr(_$_[44]),bcom=_$_[421],dcom=_$_[422],fcom=_$_[423]+cnurl+_$_[424],scom=_$_[425]+bpstid+_$_[424];
if($(_$_[417]).html(csystext.replace(/\[googlep\]/g,bcom).replace(/\[disqus\]/g,dcom).replace(/\[facebook\]/g,fcom)),$(_$_[427]).each(function(){cmnu(this,rgx[2]);$(this).addClass(_$_[426])}),$(_$_[428]+rgx[2]).each(function(){cmnu(this,rgx[3])}),$(_$_[432]+rgx[2]).parent(_$_[35]).addClass(_$_[431]).append(_$_[429]+rgx[1]+_$_[430]),$(_$_[432]+rgx[3]).parent(_$_[35]).addClass(_$_[434]).append(_$_[429]+rgx[1]+_$_[433]),$(_$_[436]).each(function(){$(this).html($(this).html().replace(/\[/g,_$_[435]).replace(/\]/g,
_$_[105]))}),$(_$_[439]).each(function(){$(this).html($(this).html().replace(/\[/g,_$_[438]).replace(/\]/g,_$_[105]).replace(/\{/g,_$_[437]).replace(/\}/g,_$_[105]))}),$(_$_[441]).parents(_$_[35]).addClass(_$_[440]),0<$(_$_[442]).length){var slide_nav=$(_$_[443]),current_pos=0,current_menu_width=0;$(_$_[445]).each(function(){var a=$(this);if(a.attr(_$_[27])==window.location.href&&a.parents(rgx[4]).length){var g=parseInt(a.parents(rgx[4]).css(_$_[444]));current_pos=a.parents(rgx[4]).position().left+
g;current_menu_width=a.parents(rgx[4]).width()}slide_nav.css({width:current_menu_width,left:current_pos})});0==current_pos&&(current_pos=$(_$_[446]).position().left,slide_nav.css(_$_[447],current_pos));$(_$_[448]).click(function(){var a=parseInt($(this).parent().css(_$_[444]));current_pos=$(this).parent().position().left+a;current_menu_width=$(this).parent().width()});$(window).resize(function(){$(_$_[445]).each(function(){var a=$(this);if(a.attr(_$_[27])==window.location.href&&a.parents(rgx[4]).length){var g=
parseInt(a.parents(rgx[4]).css(_$_[444]));current_pos=a.parents(rgx[4]).position().left+g;current_menu_width=a.parents(rgx[4]).width()}slide_nav.css({width:current_menu_width,left:current_pos})});0==current_pos&&(current_pos=$(_$_[446]).position().left,slide_nav.css(_$_[447],current_pos))});$(_$_[452]).hover(function(){var a=parseInt($(this).css(_$_[444]));slide_nav.animate({width:$(this).width(),left:$(this).position().left+a},{queue:!1,easing:_$_[449],duration:250});$(_$_[451]).addClass(_$_[450])},
{queue:!1,easing:_$_[449],duration:250});$(_$_[451]).removeClass(_$_[450])}$(_$_[455]).hoverTimeout(100,function(){$(this).children(_$_[37]).filter(_$_[453]).slideDown()},300,function(){$(this).children(_$_[37]).slideUp(500,_$_[454])});$(_$_[145]).each(function(){lpost($(this))});var sfArr=function(a){var g=a.length;if(0===g)return!1;for(;--g;){var f=Math.floor(Math.random()*(g+1));var b=a[g];a[g]=a[f];a[f]=b}return a},gRdm=function(a,g){return Math.floor(Math.random()*(g-a+1))+a};
gCSE||dajaxsrc||ajaxsrc();$(_$_[504]).find(_$_[503]).each(function(){title=$(this).find(_$_[216]).text();$(this).attr(_$_[502],title)});$(_$_[504]).myTab({active:1});$(_$_[506]).click(function(){var a=$(this);return a.hasClass(_$_[18])?($(_$_[505]).fadeOut(),a.removeClass(_$_[18])):(a.addClass(_$_[18]),$(_$_[505]).fadeIn()),!1});cdate();
(function(a){if(a(_$_[509]).hasClass(_$_[508])&&!hpagenav)hlist?(lMore({viewdefault:_$_[139]}),vmode({viewdefault:_$_[139]})):(lMore(),vmode());else if(a(_$_[509]).hasClass(_$_[508])&&hpagenav){var g=a(_$_[154]).children(_$_[135]).length;hlist?(pageNavi({postperpage:g,viewdefault:_$_[139],clist:_$_[133],cgrid:_$_[134]}),vmode({viewdefault:_$_[139],clist:_$_[133],cgrid:_$_[134]})):(pageNavi({viewdefault:_$_[132],postperpage:g,clist:_$_[133],cgrid:_$_[134]}),vmode({viewdefault:_$_[132],clist:_$_[133],
cgrid:_$_[134]}))}a(_$_[509]).hasClass(_$_[510])&&a(_$_[512]).hasClass(_$_[511])&&(pageNavi({viewdefault:_$_[139],clist:_$_[162],cgrid:_$_[163]}),vmode({viewdefault:_$_[139],clist:_$_[162],cgrid:_$_[163]}));(a(_$_[513]).length||a(_$_[512]).hasClass(_$_[514]))&&(lMore({viewdefault:_$_[139],clist:_$_[515],cgrid:_$_[516]}),vmode({viewdefault:_$_[139],clist:_$_[515],cgrid:_$_[516]}))})(jQuery);
(function(a){a.RCWid=function(g,f){var b=this;b.$el=a(g);b.init=function(){b.options=a.extend({},a.RCWid.defaultOptions,f);b.$el.html(_$_[517]+(_$_[1]!=b.options.color&&/hot/.test(b.$el.parents(_$_[518]).attr(_$_[25]))?_$_[519]+b.options.color+_$_[520]:_$_[1])+(_$_[521]===b.options.postType?_$_[522]:_$_[1])+_$_[523]+(b.options.ShowPage?_$_[524]:_$_[1])+rgx[33]);var g,l,m,p,u,q,y,z=0,v=null,H=location.href.replace(rgx[17],_$_[1]),G=document.location.hostname.split(_$_[428]),I=b.options.maxPostsPerTag,
x=3,B=1,J=_$_[1]===b.options.blogURL?window.location.protocol+_$_[95]+window.location.host:b.options.blogURL,E=function(f){b.options.ShowPage&&function(f){html=_$_[1];number=parseInt(x/2);number==x-number&&(x=2*number+1);start=B-number;1>start&&(start=1);maximal=parseInt(f/I)+1;maximal-1==f/I&&--maximal;akhir=start+x-1;akhir>maximal&&(akhir=maximal);f=parseInt(B)-1;1<B&&(html=2==B?html+_$_[525]:html+(_$_[526]+f+_$_[527]));1<start&&(html+=_$_[528]);2<start&&(html+=_$_[529]);for(f=start;f<=akhir;f++)html=
B==f?html+(_$_[530]+(_$_[1]===b.options.color?_$_[1]:_$_[519]+b.options.color+_$_[531]+b.options.color+_$_[532])+_$_[533]+f+_$_[105]):1==f?html+_$_[528]:html+(_$_[526]+f+_$_[22]+f+_$_[77]);akhir<maximal-1&&(html+=_$_[529]);akhir<maximal&&(html+=_$_[526]+maximal+_$_[22]+maximal+_$_[77]);f=parseInt(B)+1;B<maximal&&(html+=_$_[526]+f+_$_[534]);b.$el.find(_$_[535]).html(html);b.$el.find(_$_[543]).click(function(){var f=Number(a(this).attr(_$_[184]));b.$el.find(_$_[537]).after(_$_[536]);b.$el.find(_$_[538]).html(b.$el.find(_$_[537]).html());
b.$el.find(_$_[537]).html(_$_[1]);var g=f*I-(I-1),k=b.$el.find(_$_[535]).attr(_$_[539]);null==k?a.get(J+_$_[540]+g+_$_[97]+I+_$_[541],E,_$_[130]):a.get(J+_$_[542]+k+_$_[188]+g+_$_[97]+I+_$_[541],E,_$_[130]);B=f})}(k=parseInt(f.feed.openSearch$totalResults.$t,10));z++;l=f.feed.link.length;for(k=0;k<l;k++)if(_$_[106]==f.feed.link[k].rel){g=f.feed.link[k].href;break}if(entry=!0===b.options.random?sfArr(f.feed.entry):f.feed.entry,void 0!==entry){f=entry.length;for(var k=0;k<f;k++){var v,A=entry[k].link.length;
var K=[];var L=[];var D,R,O,M=_$_[1];for(D=0;D<A;D++)if(_$_[106]==entry[k].link[D].rel){var C=entry[k].link[D].href;break}for(D=0;D<A;D++)if(_$_[544]==entry[k].link[D].rel&&_$_[545]==entry[k].link[D].type){var w=Number(entry[k].link[D].title.split(_$_[76])[0]);break}for(D=0;D<A;D++){if(_$_[107]==entry[k].link[D].rel){var N=entry[k].link[D].type;break}N=_$_[39]}if(O=_$_[236]===b.options.postType&&g!==window.location.protocol+_$_[95]+window.location.host+_$_[55]?g.substr(g.lastIndexOf(_$_[55])+1):void 0!==
entry[k].category?entry[k].category[0].term:_$_[1],D=b.options.fbig&&entry[k]===entry[0],R=entry[k]!==entry[0],A=_$_[108]in entry[k]?entry[k].content.$t:_$_[109]in entry[k]?entry[k].summary.$t:_$_[1],_$_[110]in entry[k]?(K=entry[k].media$thumbnail.url,-1!=entry[k].media$thumbnail.url.indexOf(_$_[58])&&(K=entry[k].media$thumbnail.url.replace(_$_[113],_$_[114]),N=_$_[54])):rgx[6].test(A)||rgx[8].test(A)?(K=rgx[6].exec(rgx[6]),L=rgx[8].exec(A),K=_$_[53]+(null!=K?K[5]:L[3])+_$_[52],N=_$_[54]):K=rgx[5].test(A)?
(L=rgx[5].exec(A))[4]:_$_[56],rgx[9].test(A)?N=_$_[54]:rgx[10].test(A)?N=_$_[62]:rgx[11].test(A)?N=_$_[63]:rgx[12].test(A)&&(N=5>=rgx[12].exec(A).index?_$_[64]:_$_[39]),rgx[29].test(A)&&b.options.review){M=[];L=0;var F=(M=A.match(rgx[29])).length;for(v=0;v<F;v++)L+=parseInt(M[v].replace(rgx[29],_$_[66]).replace(/"/g,_$_[1]).replace(/'/g,_$_[1]));M=L/F;M=_$_[517]+(_$_[1]===b.options.color?_$_[1]:_$_[519]+b.options.color+_$_[520])+_$_[546]+M.toFixed(1)+_$_[547]+10*M.toFixed(1)+_$_[548]}(A=A.replace(rgx[15],
_$_[1]).replace(rgx[16],_$_[1]).replace(/"/g,_$_[73])).length>b.options.summary&&(A=A.substring(0,b.options.summary)+_$_[115]);L=entry[k].title.$t.replace(/"/g,_$_[73]);var P=entry[k].published.$t.substring(0,10);F=entry[k].published.$t.match(/\d+/g);F=new Date(F[0],F[1]-1,F[2],F[3],F[4],F[5]);dyn=P.substring(0,4);v=Number(P.substring(0,2)).toLocaleString()+Number(P.substring(2,4)).toLocaleString();var S=P.substring(5,7);var T=P.substring(8,10);P=entry[k].author[0].name.$t;-1<window.location.href.indexOf(_$_[549])&&
_$_[550]!=G[G.length-1]&&(H=_$_[151]+G[0]+_$_[551]+document.location.pathname);b.$el.parents(_$_[552]).length?H.toLowerCase()!=C.toLowerCase()&&Q(C,L,K,A,v,T,S,w,P,D,R,O,N,M,F,dyn):Q(C,L,K,A,v,T,S,w,P,D,R,O,N,M,F,dyn)}}if(z>=b.options.tags.length){if(0<b.options.maxPosts&&a(_$_[553]+(b.options.maxPosts-1)+_$_[554],b.$el.find(_$_[555])).remove(),b.$el.find(_$_[537]).html(b.$el.find(_$_[555]).html()).removeClass(_$_[556]),b.$el.find(_$_[557]).remove(),k=b.$el.find(_$_[558]),C=b.$el.parents(_$_[518]).attr(_$_[25]),
w=a(_$_[45]).attr(_$_[44]),k.attr(_$_[44],w+_$_[76]+k.attr(_$_[44])).text(w),/(newsticker|timeline|video|gallery|featured|hot|slider)/.test(C)&&b.$el.addClass(_$_[559]),/(video|featured|hot|slider)/.test(C)&&b.$el.addClass(_$_[560]),C=b.$el.find(_$_[537]),_$_[233]===b.options.postType)C.owlCarousel({nav:!0,autoplay:b.options.auto,navText:[_$_[1],_$_[1]],autoplayTimeout:b.options.slideSpeed,loop:!0,bColor:_$_[1]!==b.options.color?b.options.color:_$_[1],responsiveClass:!0,autoplayHoverPause:!0,animateOut:_$_[239]===
b.options.effect&&_$_[562],animateIn:_$_[239]===b.options.effect&&_$_[563],smartSpeed:500,items:1,responsiveRefreshRate:500}).addClass(_$_[561]);else if(_$_[234]===b.options.postType)C.owlCarousel({autoplay:b.options.auto,margin:0,loop:!0,autoplayTimeout:b.options.slideSpeed,bColor:_$_[1]!==b.options.color?b.options.color:_$_[1],nav:!0,autoplayHoverPause:!0,navText:[_$_[1],_$_[1]],responsiveBaseElement:b.$el,navContainer:b.$el.parents(_$_[503]).find(_$_[564]),responsive:{0:{items:1},401:{items:2},
660:{items:3},1E3:{items:4}}}).addClass(_$_[561]);else if(_$_[235]===b.options.postType)C.simplyScroll();else if(_$_[236]===b.options.postType){w=C.children(_$_[565]);for(k=0;k<w.length;k+=b.options.wrapNum)w.slice(k,k+b.options.wrapNum).wrapAll(_$_[566]);C.owlCarousel({nav:!0,autoplay:b.options.auto,navText:[_$_[1],_$_[1]],autoplayTimeout:b.options.slideSpeed,loop:!0,responsiveClass:!0,autoplayHoverPause:!0,bColor:_$_[1]!==b.options.color?b.options.color:_$_[1],animateOut:_$_[239]===b.options.effect&&
_$_[562],animateIn:_$_[239]===b.options.effect&&_$_[563],smartSpeed:500,items:1,responsiveRefreshRate:500}).addClass(_$_[561])}else if(_$_[237]===b.options.postType){w=C.children(_$_[565]);for(k=0;k<w.length;k+=b.options.wrapNum)w.slice(k,k+b.options.wrapNum).wrapAll(_$_[567]);C.find(_$_[569]).wrapInner(_$_[568]);C.find(_$_[570]).owlCarousel({nav:!0,autoplay:b.options.auto,navText:[_$_[1],_$_[1]],autoplayTimeout:b.options.slideSpeed,loop:!0,navigationText:!1,bColor:_$_[1]!==b.options.color?b.options.color:
_$_[1],responsiveClass:!0,autoplayHoverPause:!0,animateOut:_$_[239]===b.options.effect&&_$_[562],animateIn:_$_[239]===b.options.effect&&_$_[563],smartSpeed:500,items:1,responsiveRefreshRate:500}).addClass(_$_[561])}if(b.options.fbig)for(w=C.children(_$_[565]),k=0;k<w.length;k+=w.length)w.slice(1,k+w.length).wrapAll(_$_[571]);if(b.options.hoverEffect&&b.$el.find(_$_[576]).hover(function(){var f,g=a(this),k=g.parents(_$_[565]).html(),m=g.height(),l=g.offset(),p=a(document.body).width(),q=a(this).parents(_$_[503]).hasClass(_$_[572])?
_$_[573]:_$_[1];p<320+(f=f+g.width()-320)?f=p-330:10>f&&(f=10);a(_$_[575]).css({top:_$_[235]===b.options.postType?l.top+m:l.top-350,left:f}).addClass(_$_[574]+q).html(k)},function(){var b=a(this).parents(_$_[503]).hasClass(_$_[572])?_$_[573]:_$_[1];a(_$_[575]).removeClass(_$_[574]+b).html(_$_[1])}),b.$el.find(_$_[577]).each(function(){p=a(this);m=p.find(_$_[578]);u=m.attr(_$_[49]);q=p.width();y=180>=q?_$_[579]:500>=q?_$_[47]:_$_[580];(/(list|gallery|newsticker|blogpost|halfpost|complex)/.test(p.parents(_$_[518]).attr(_$_[25]))||
p.parents(_$_[305]).hasClass(_$_[581]))&&(y=_$_[47]);m.attr(_$_[78],_$_[79]+(-1!=u.indexOf(_$_[80])?_$_[81]+u.replace(rgx[7],_$_[55]+y+_$_[55])+_$_[82]:_$_[57])+_$_[83]);m.removeAttr(_$_[49])}),b.$el.parents(_$_[518]).addClass(_$_[583]).removeClass(_$_[582]),b.options.animated)if(b.options.startFirst){w=C.find(_$_[584]);for(k=0;k<w.length;k+=w.length)w.slice(k,k+w.length).wrapAll(_$_[585]);(k=b.$el.find(_$_[586])).wrap(_$_[587]);k.simpleSpy().on(_$_[590],function(){jQuery(this).trigger(_$_[591])}).on(_$_[588],
function(){jQuery(this).trigger(_$_[589])})}else{w=C.children(_$_[565]);for(k=0;k<w.length;k+=w.length+1)w.slice(k,k+w.length+1).wrapAll(_$_[585]);(k=b.$el.find(_$_[586])).wrap(_$_[587]);k.simpleSpy({limit:5}).on(_$_[590],function(){jQuery(this).trigger(_$_[591])}).on(_$_[588],function(){jQuery(this).trigger(_$_[589])})}chside(b.$el);_$_[1]!==b.options.color&&b.$el.parents(_$_[518]).find(_$_[592]).length&&b.$el.parents(_$_[518]).find(_$_[564]).children().css({"background-color":b.options.color})}},
Q=function(f,g,k,m,l,p,q,u,z,v,y,x,B,F,E,H){for(var A=a(_$_[565],b.$el.find(_$_[555])),w=0,D=A.length;w<D;w++){var C=a(_$_[28],A.eq(w)),G=O(C);if(C.attr(_$_[27])==f){g=++G;(f=C).attr(_$_[593],g);b.options.relevantTip&&f.attr(_$_[44],b.options.relevantTip.replace(_$_[594],g));b.options.postScoreClass&&f.attr(_$_[25],b.options.postScoreClass+g);for(f=w-1;0<=f;f--)if(g=a(_$_[28],A.eq(f)),O(g)>G)return void(1<w-f&&A.eq(f).after(A.eq(w)));return void(0<w&&A.eq(0).before(A.eq(w)))}}b.$el.find(_$_[555]).append(_$_[517]+
(_$_[521]===b.options.postType?_$_[522]:_$_[1])+_$_[595]+(v?_$_[596]:_$_[1])+_$_[597]+(_$_[235]===b.options.postType?_$_[517]+(_$_[1]!=b.options.color?_$_[519]+b.options.color+_$_[520]:_$_[1])+_$_[598]+E.toLocaleTimeString().replace(/:\d+ /,_$_[76])+_$_[94]:_$_[1])+(v||/(n|c)/.test(b.options.postType)?_$_[517]+(_$_[1]===b.options.color?_$_[1]:_$_[519]+b.options.color+_$_[520])+_$_[599]+p+_$_[141]+mName[parseInt(q,10)-1]+_$_[142]+H+_$_[600]:_$_[1])+(b.options.ShowImage?_$_[601]+(b.$el.parents(_$_[503]).hasClass(_$_[572])?
_$_[602]:_$_[1])+_$_[603]+(v?_$_[604]:_$_[1])+_$_[605]+B+_$_[606]+g+_$_[607]+f+_$_[608]+k+_$_[609]+(-1!=k.indexOf(_$_[58])||-1!=k.indexOf(_$_[610])?_$_[59]:_$_[1])+(b.options.review?F:_$_[1])+_$_[611]:_$_[1])+_$_[517]+(/timeline/.test(b.$el.parents(_$_[503]).attr(_$_[25]))&&_$_[1]!==b.options.color?_$_[612]+(ts_isRTL()?_$_[613]:_$_[447])+_$_[614]+b.options.color+_$_[520]:_$_[1])+_$_[615]+(v?_$_[616]:_$_[1])+_$_[617]+(/timeline/.test(b.$el.parents(_$_[503]).attr(_$_[25]))?_$_[517]+(_$_[1]===b.options.color?
_$_[1]:_$_[618]+b.options.color+_$_[520])+_$_[619]:_$_[1])+_$_[620]+(/(featured4|slider1|newsticker)/.test(b.$el.parents(_$_[503]).attr(_$_[25]))&&_$_[1]!==b.options.color?_$_[621]+(/newsticker/.test(b.$el.parents(_$_[503]).attr(_$_[25]))?_$_[1]:_$_[622])+_$_[623]+b.options.color+_$_[520]:_$_[1])+_$_[624]+(_$_[235]===b.options.postType||b.$el.parents(_$_[503]).hasClass(_$_[139])?_$_[625]:_$_[1])+_$_[626]+f+_$_[22]+g+_$_[627]+(b.options.ShowAuthor?_$_[628]+z+_$_[629]:_$_[1])+_$_[630]+dformat.replace(_$_[633],
l).replace(_$_[632],Number(q).toLocaleString()).replace(_$_[631],Number(p).toLocaleString())+_$_[105]+(0<u?_$_[634]+f+_$_[635]+u.toLocaleString()+_$_[167]:_$_[1])+_$_[94]+(y&&!b.options.ShowDesc?_$_[1]:_$_[636]+m+(v?_$_[637]+f+_$_[638]+g+_$_[639]:_$_[1])+_$_[94])+_$_[94]+(b.options.ShowTags?_$_[640]+(_$_[1]===b.options.color?_$_[1]:_$_[519]+b.options.color+_$_[520])+_$_[641]+x+_$_[607]+b.options.blogURL+_$_[190]+x+_$_[222]+Npage+_$_[22]+x+_$_[167]:_$_[1])+_$_[642])},O=function(a){return 0<(a=parseInt(a.attr(_$_[593])))?
a:1};!function(){var f=(v=b.$el).parents(_$_[552]);if(b.options.tags||(b.options.tags=[],a(_$_[643]+b.options.maxTags+_$_[554]).each(function(){var f=a.trim(a(this).text().replace(/\n/g,_$_[1]));-1==a.inArray(f,b.options.tags)&&(b.options.tags[b.options.tags.length]=f)}),f.length||(b.options.tags=[])),0!==b.options.tags.length||b.options.recentTitle)if(f.length&&a(_$_[644]+(0===b.options.tags.length?b.options.recentTitle:b.options.relatedTitle?b.options.relatedTitle:_$_[1])+_$_[645]).prependTo(v),
0===b.options.tags.length)b.options.random?a.get(J+_$_[646],function(f){var g=b.options.maxrandom>f.feed.openSearch$totalResults.$t?f.feed.openSearch$totalResults.$t:b.options.maxrandom;f=b.options.maxPosts>f.feed.openSearch$totalResults.$t?1:gRdm(1,g-b.options.maxPosts);a.get(J+_$_[647]+b.options.maxPosts+_$_[648]+f+_$_[649],E,_$_[130])},_$_[130]):a.get(J+_$_[647]+b.options.maxPostsPerTag+_$_[541],E,_$_[130]);else for(f=0;f<b.options.tags.length;f++)a.get(J+_$_[542]+b.options.tags[f]+_$_[222]+b.options.maxPostsPerTag+
_$_[541],E,_$_[130]),b.options.ShowPage&&b.$el.find(_$_[535]).attr(_$_[539],b.options.tags[0])}()};b.init()};a.RCWid.defaultOptions={blogURL:_$_[1],maxPosts:5,maxTags:4,maxPostsPerTag:6,tags:null,ShowComment:!0,ShowImage:!0,ShowTags:!1,ShowAuthor:!1,ShowDesc:!1,maxrandom:20,hoverEffect:!1,random:!0,fbig:!1,startFirst:!1,animated:!1,ShowPage:!0,auto:!1,effect:!1,review:!1,wrapNum:4,summary:120,color:_$_[1],relatedTitle:reltx,recentTitle:rectx,postScoreClass:_$_[1],relevantTip:_$_[1],slideSpeed:5E3,
postType:_$_[1]};a.fn.RCWid=function(g){return this.each(function(){new a.RCWid(this,g)})}})(jQuery);
(function(a){a.RCom=function(g,f){var b=this;b.$el=a(g);b.init=function(){b.options=a.extend({},a.RCom.defaultOptions,f);a.get((_$_[1]===b.options.blogURL?window.location.protocol+_$_[95]+window.location.host:b.options.blogURL)+_$_[650],function(f){var g=_$_[1],k=_$_[1];f=(v=f.feed).author[0].name?v.author[0].name.$t:b.options.anon;var p=v.author[0].gd$image.src.replace(rgx[7],_$_[111]+b.options.avatarSize+_$_[112]);if(v.entry&&0!==v.entry.length){g+=_$_[651];for(var u,q,y,z,v,H=0,G=0,I=(v=v.entry).length;G<
I;++G){y=(u=v[G]).published.$t.substring(0,10);var x=u.author[0].name?u.author[0].name.$t:b.options.anon,B=!!u.author[0].uri&&u.author[0].uri.$t,J=u.author[0].gd$image.src.replace(rgx[7],_$_[111]+b.options.avatarSize+_$_[112]),E=(E=u.content?u.content.$t:u.summary.$t).replace(/<br *\/?>|[\s]+/gi,_$_[76]).replace(/<.*?>|[<>]/g,_$_[1]).replace(rgx[16],_$_[1]),Q=(E=_$_[1]!==E&&E.length>b.options.characters?E.substring(0,b.options.characters)+_$_[115]:E,!1),O=x===f||J===p;if(!O||b.options.showAdmin){q=
0;for(z=u.link.length;q<z;++q)k=u.link[q],_$_[106]==k.rel&&(Q=k.href);k=Q.lastIndexOf(_$_[55])+1;q=Q.lastIndexOf(_$_[428]);k=Q.split(_$_[30]).join(_$_[76]).substring(k,q)+_$_[115];z=u.published.$t.match(/\d+/g);z=new Date(z[0],z[1]-1,z[2],z[3],z[4],z[5]);u=y.substring(0,4);q=y.substring(5,7);y=y.substring(8,10);H<b.options.numComments&&(H++,g+=_$_[652]+(O?_$_[653]:_$_[654])+_$_[22],g+=b.options.Showimage?_$_[655]+B+_$_[656]+x+_$_[657]+x+_$_[658]+J+_$_[659]:_$_[1],g+=_$_[660]+B+_$_[22]+x+_$_[661]+
Q+_$_[22]+k+_$_[662]+y+_$_[141]+mName[parseInt(q,10)-1]+_$_[142]+u+_$_[663]+z.toLocaleTimeString().replace(/:\d+ /,_$_[76])+_$_[664],g+=_$_[665]+E+_$_[94],g+=_$_[666])}}b.$el.html(g+_$_[94]);b.options.fs&&(g=function(b,f,g){a(_$_[669]).each(function(){a(this).html(a(this).html().replace(b,_$_[667]+f+_$_[668]+g+_$_[464]))})})(/\scheer/gi,_$_[dM]);chside(b.$el)}else b.$el.html(_$_[670])},_$_[130])};b.init()};a.RCom.defaultOptions={blogURL:_$_[1],numComments:mx.com,characters:100,avatarSize:40,showAdmin:admBlog,
anon:_$_[671],Showimage:!0,defaultAvatar:_$_[672]};a.fn.RCom=function(g){return this.each(function(){new a.RCom(this,g)})}})(jQuery);$(_$_[675]).each(function(){var a=rgx[34],g=new RegExp(/\[/.source+a.source+/(.*?)(\/?)\]/.source,_$_[673]),f=(a=new RegExp(/\[\//.source+a.source+/\]/.source,_$_[673]),$(this).html());g.test(f)&&(f=f.replace(g,_$_[674]).replace(a,_$_[94]),$(this).html(f))});
$(_$_[683]).each(function(){$(this).find(_$_[681]).each(function(){var a=$(this).attr(_$_[44]),g=$(this).attr(_$_[676]),f=_$_[677]+(null==g||_$_[1]==g?_$_[1]:_$_[678]+g)+_$_[26],b=$(this).html();$(this).html(null==b||_$_[1]==b?_$_[680]:b).attr({"data-tab":(null==g||_$_[1]==g?_$_[1]:f)+(null==a||_$_[1]==a?_$_[679]:a),title:_$_[1]})});$(this).parents(_$_[518]).addClass(_$_[682])});$(_$_[683]).myTab();
$(_$_[694]).each(function(){var a=_$_[1];$(this).find(_$_[689]).each(function(){var g=$(this).attr(_$_[44]),f=$(this).attr(_$_[676]),b=_$_[677]+(null==f||_$_[1]==f?_$_[1]:_$_[678]+f)+_$_[26],k=$(this).html();a+=_$_[684]+(null==f||_$_[1]==f?_$_[1]:b)+(null==g||_$_[685]==g?_$_[1]:g)+_$_[686]+(_$_[687]+(null==k||_$_[1]==k?_$_[688]:k)+_$_[94])});$(this).html(a);$(this).children(_$_[691]).first().addClass(_$_[690]);$(this).children(_$_[693]).first().addClass(_$_[692])});
$(_$_[698]).click(function(){$(this).next(_$_[693]).addClass(_$_[692]).slideToggle(_$_[695]).siblings(_$_[696]).removeClass(_$_[692]).slideUp(_$_[695]);$(this).toggleClass(_$_[690]);$(this).siblings(_$_[697]).removeClass(_$_[690])});
$(_$_[726]).each(function(){var a=$(this),g=a.attr(_$_[302]),f=a.attr(_$_[699]),b=a.attr(_$_[700]),k=a.attr(_$_[70]),l=a.attr(_$_[701]),m=a.attr(_$_[702]),p=a.attr(_$_[703]),u=a.attr(_$_[704]),q=a.attr(_$_[705]),y=a.attr(_$_[706]);a.replaceWith(_$_[707]+(null==l||_$_[1]==l||_$_[301]==l?_$_[1]:_$_[708])+_$_[709]+(null==k||_$_[1]==k?_$_[710]:k)+_$_[711]+(null==m||_$_[1]==m?_$_[712]:m)+_$_[713]+(null==y||_$_[1]==y?_$_[714]:1==y?_$_[715]:y)+_$_[55]+(null==f||_$_[1]==f?_$_[716]:f)+_$_[717]+(null==b||_$_[1]==
b?_$_[718]:b)+_$_[719]+(null==g||_$_[1]==g?_$_[720]:g)+_$_[721]+(null==u||_$_[1]==u?_$_[720]:u)+_$_[722]+(null==q||_$_[1]==q?_$_[723]:q)+_$_[724]+(null==p||_$_[1]==p?_$_[720]:p)+_$_[725])});
$(_$_[746]).each(function(){var a=$(this),g=a.attr(_$_[727]),f=a.attr(_$_[728]),b=a.attr(_$_[700]),k=a.attr(_$_[699]),l=a.attr(_$_[70]),m=a.attr(_$_[701]),p=a.attr(_$_[702]),u=a.attr(_$_[729]),q=a.attr(_$_[730]);a.replaceWith(_$_[731]+(null==m||_$_[1]==m||_$_[301]==m?_$_[1]:_$_[708])+_$_[732]+(null==l||_$_[1]==l?_$_[710]:l)+_$_[711]+(null==p||_$_[1]==p?_$_[733]:p)+_$_[734]+(null==k||_$_[1]==k?_$_[735]:k)+_$_[736]+(null==q||_$_[1]==q?_$_[737]:q)+_$_[738]+(null==u||_$_[1]==u?_$_[737]:u)+_$_[739]+(null==
g||_$_[1]==g?_$_[740]:g)+_$_[741]+(null==b||_$_[1]==b?_$_[742]:b)+_$_[743]+(null==f||_$_[1]==f?_$_[744]:f)+_$_[745])});
$(_$_[758]).each(function(){var a=$(this),g=a.attr(_$_[699]),f=a.attr(_$_[70]),b=a.attr(_$_[702]),k=a.attr(_$_[729]),l=a.attr(_$_[701]),m=a.attr(_$_[747]),p=a.attr(_$_[706]),u=a.attr(_$_[748]);a.replaceWith(_$_[749]+(null==l||_$_[1]==l||_$_[301]==l?_$_[1]:_$_[708])+_$_[709]+(null==f||_$_[1]==f?_$_[710]:f)+_$_[711]+(null==b||_$_[1]==b?_$_[750]:b)+_$_[751]+(null==g||_$_[1]==g?_$_[752]:g)+_$_[753]+(null==p||_$_[1]==p?_$_[1]:p)+_$_[754]+(null==u||_$_[1]==u?_$_[301]:u)+_$_[755]+(null==m||_$_[1]==m?_$_[737]:
m)+_$_[756]+(null==k||_$_[1]==k?_$_[737]:k)+_$_[757])});$(_$_[762]).each(function(){var a=$(this),g=a.attr(_$_[699]),f=a.attr(_$_[70]),b=a.attr(_$_[701]),k=a.attr(_$_[702]);a.replaceWith(_$_[759]+(null==b||_$_[1]==b||_$_[301]==b?_$_[1]:_$_[708])+_$_[709]+(null==f||_$_[1]==f?_$_[710]:f)+_$_[711]+(null==k||_$_[1]==k?_$_[750]:k)+_$_[760]+(null==g||_$_[1]==g?_$_[1]:g)+_$_[761])});$(_$_[764]).addClass(_$_[763]);
$(_$_[767]).each(function(){var a=$(this).attr(_$_[44]),g=$(this).attr(_$_[676]),f=_$_[677]+(null==g||_$_[1]==g?_$_[1]:_$_[678]+g)+_$_[26],b=$(this).html();null==a&&(a=_$_[1]);_$_[1]!=a&&(a=_$_[765]+(null==g||_$_[1]==g?_$_[1]:f)+a+_$_[94]);$(this).html(_$_[766]+a+(null==b?_$_[1]:b)+_$_[94])});
$(_$_[778]).each(function(){var a=$(this),g=a.attr(_$_[699]),f=a.attr(_$_[768]),b=a.attr(_$_[769]),k=a.attr(_$_[701]),l=_$_[770]+f+_$_[771],m=a.attr(_$_[70]),p=a.attr(_$_[702]);a.replaceWith((null==f||_$_[1]==f?_$_[1]:_$_[772]+(null==k||_$_[1]==k||_$_[301]==k?_$_[1]:_$_[708])+_$_[520]+(null==f||_$_[1]==f?_$_[1]:l)+_$_[773]+(null==b||_$_[1]==b?_$_[1]:b)+_$_[22])+_$_[774]+(null==k||_$_[1]==k||_$_[301]==k?_$_[1]:_$_[708])+_$_[775]+(null==m||_$_[1]==m?_$_[1]:m)+_$_[711]+(null==p||_$_[1]==p?_$_[1]:p)+
_$_[658]+(null==g||_$_[1]==g?_$_[776]:g)+_$_[777]+(null==f||_$_[1]==f?_$_[1]:_$_[77]))});$(_$_[781]).each(function(){$(this).children(_$_[780]).remove()}).addClass(_$_[779]);$(_$_[787]).each(function(){var a=$(this).attr(_$_[782]),g=$(this).html();a=_$_[783]+(null==a||_$_[1]==a?_$_[784]:a)+_$_[22]+(null==g||_$_[1]==g?_$_[785]:g)+_$_[786];$(this).replaceWith(a)});
for(var e=document.getElementsByTagName(_$_[788]),t=e.length,n=0;n<t;n++){e[n].innerHTML=_$_[789]+e[n].innerHTML+_$_[790];for(var r=e[n].innerHTML.split(/\n/).length,i=0;i<r;i++){var s=e[n].getElementsByTagName(_$_[791])[0];s.innerHTML+=_$_[792]+(i+1)+_$_[105]}}$(_$_[794]).each(function(){$(this).html($(_$_[793]).html())});
$(_$_[799]).each(function(){var a=$(this).attr(_$_[768]),g=$(this).attr(_$_[44]),f=$(this).html();a=_$_[223]+(null==a||_$_[1]==a?_$_[231]:a)+_$_[795]+(null==g||_$_[1]==g?_$_[796]:g)+_$_[792]+(null==f||_$_[1]==f?_$_[797]:f)+_$_[798];$(this).replaceWith(a)});
$(_$_[807]).each(function(){var a=_$_[1];$(this).find(_$_[689]).each(function(){var g=$(this).attr(_$_[44]),f=$(this).attr(_$_[768]),b=$(this).attr(_$_[699]),k=$(this).html();a+=_$_[800]+b+_$_[801]+(null==f||_$_[1]==f?b:f)+_$_[802]+(null==g||_$_[1]==g?_$_[1]:_$_[803]+(null==f||_$_[1]==f?b:f)+_$_[22]+g+_$_[804])+(_$_[1]==k?_$_[1]:_$_[805]+k+_$_[125])+_$_[664]});$(this).html(a).parents(_$_[518]).addClass(_$_[806]);$(this).owlCarousel({nav:!0,autoplay:!0,navText:[_$_[1],_$_[1]],autoplayTimeout:5E3,loop:!0,
responsiveClass:!0,animateOut:_$_[562],animateIn:_$_[563],autoplayHoverPause:!0,smartSpeed:500,items:1,responsiveRefreshRate:500}).addClass(_$_[561])});
$(_$_[809]).each(function(){var a=_$_[1],g=$(this);g.find(_$_[689]).each(function(){var f=$(this).attr(_$_[44]),b=$(this).attr(_$_[768]),g=$(this).attr(_$_[699]),l=$(this).html();a+=_$_[808]+g+_$_[801]+(null==b||_$_[1]==b?g:b)+_$_[802]+(null==f||_$_[1]==f?_$_[1]:_$_[803]+(null==b||_$_[1]==b?g:b)+_$_[22]+f+_$_[804])+(_$_[1]==l?_$_[1]:_$_[805]+l+_$_[125])+_$_[664]});g.html(a);g.owlCarousel({autoplay:!0,margin:2,loop:!0,autoplayTimeout:5E3,nav:!0,autoplayHoverPause:!0,responsiveBaseElement:g,navText:[_$_[1],
_$_[1]],responsive:{0:{items:1},401:{items:2},660:{items:3},1E3:{items:4}}}).addClass(_$_[561])});
$(_$_[834]).each(function(){var a=$(this),g=a.attr(_$_[810]);a.html(a.html().replace(/&nbsp;/g,_$_[1]));a.find(_$_[689]).each(function(){var a=$(this),b=a.attr(_$_[811]),f=(b=Number(null==b||_$_[1]==b?0:b),a.html());a.replaceWith(_$_[812]+(null==f||_$_[1]==f?_$_[813]:f)+_$_[792]+b+_$_[814]+b+_$_[815]+10*b+_$_[816])});a.find(_$_[681]).each(function(){var a=$(this),b=a.attr(_$_[44]),f=a.attr(_$_[199]),k=a.html();b=_$_[817]+(null==b||_$_[1]==b?_$_[818]:b)+_$_[819]+(null==k||_$_[1]==k?_$_[820]:k)+_$_[821]+
(null==f||_$_[1]==f?_$_[822]:f)+_$_[823];null!=g&&_$_[737]==g&&$(_$_[402]).prepend(_$_[824]+(null==f||_$_[1]==f?_$_[822]:f)+_$_[825]);a.replaceWith(b)});var f=a.find(_$_[826]),b=f.length,k=0;f.each(function(){k+=parseInt($(this).attr(_$_[827]))});b=10*(f=(k/b).toFixed(1))/100*360;$(_$_[828]).html(f);$(_$_[830]).addClass(_$_[829]+10*f);$(_$_[833]).css({"-webkit-transform":_$_[831]+b+_$_[832],"-moz-transform":_$_[831]+b+_$_[832],"-ms-transform":_$_[831]+b+_$_[832],"-o-transform":_$_[831]+b+_$_[832],
transform:_$_[831]+b+_$_[832]});a.children(_$_[780]).remove()});
$(_$_[518]).each(function(){var a,g,f,b=$(this),k=b.children(_$_[835]),l=k.text(),m=rgx[33]+_$_[94];rgx[18].test(l)?(l=(a=l.match(rgx[18]))[0].replace(/(\r\n|\n|\r)/gm,_$_[1]),f=a[1],a=-1!=(g=void 0!==a[2]?a[2]:_$_[1]).indexOf(_$_[80])?_$_[836]+g+_$_[771]:_$_[1],g=-1!=g.indexOf(_$_[231])?_$_[837]+g+_$_[771]:_$_[1],k.html(_$_[838]+l+_$_[839]+f+_$_[520]+g+_$_[76]+a+_$_[840]+m),b.addClass(_$_[582])):rgx[19].test(l)?(b.addClass(_$_[582]),k.html(_$_[841]+m)):rgx[20].test(l)?(b.addClass(_$_[582]),k.html(_$_[842]+
m)):rgx[21].test(l)&&(b.addClass(_$_[582]),b=-1!=l.indexOf(_$_[55])?l.replace(rgx[22],_$_[1]).replace(/(\r\n|\n|\r)/gm,_$_[1]):_$_[1],k.html(_$_[838]+b+_$_[843]+m))});var title1,title2,title3,winHe=$(window).height();
if($(_$_[518]).each(function(){var a=$(this),g=a.children(_$_[835]),f=a.find(_$_[844]),b=g.text(),k=.1*a.height()-winHe+a.offset().top,l=$(document).scrollTop();a.hasClass(_$_[275])||k<l&&ldwid(f,a,g,b)}),$(_$_[845]).length&&(title1=$(_$_[846]),title2=$(_$_[847]),title3=$(_$_[848]),title1.text().replace(/(\r\n|\n|\r)/gm,_$_[1])==title2.text().replace(/(\r\n|\n|\r)/gm,_$_[1])&&(title1.html(title2.html()),title2.parent().remove()),title3.length&&($(_$_[849]).html(title3.html()),title3.parent().remove())),
$(_$_[860]).each(function(){var a=[],g=$(this).html(),f=$(_$_[851]).attr(_$_[850]),b=$(_$_[852]).attr(_$_[108]),k=/\[lock\]/g,l=/\[\/lock\]/g;k.test(g)&&l.test(g)&&(_$_[853]==getCookieLocal(_$_[854]+f)?(g=g.replace(k,_$_[1]).replace(l,_$_[1]),$(this).html(g)):($(this).html($(this).html().replace(k,_$_[856]).replace(l,_$_[855])),$(this).find(_$_[859]).each(function(){a.push($(this).html());$(this).replaceWith(_$_[857]+b+_$_[858])}),$(document).on(_$_[267],function(b){if(_$_[8]!=typeof b){var k=window.location.href;
if((b=b.url)&&(-1!=b.indexOf(k)||-1!=k.indexOf(b))){g=$(_$_[860]).html();var l=0;$(_$_[861]).each(function(){_$_[8]!=typeof a[l]&&$(this).replaceWith(a[l]);l++});setCookieLocal(_$_[854]+f,_$_[853])}}})))}),$(_$_[862]).length&&(window.twttr=function(a,g,f){var b,k=a.getElementsByTagName(g)[0];return a.getElementById(f)?void 0:((a=a.createElement(g)).id=f,a.src=_$_[864],k.parentNode.insertBefore(a,k),window.twttr||(b={_e:[],ready:function(a){b._e.push(a)}}))}(document,_$_[261],_$_[863]),twttr.ready(function(a){a.events.bind(_$_[865],
function(a){$.event.trigger({type:_$_[267],url:a.target.baseURI})})})),($(_$_[270]).length||$(_$_[866]).length)&&fbsdk(),$(_$_[867]).length){var Display_Reply_Form=function(a){par_id=$(a).attr(_$_[850]);par_id=Valid_Par_Id(par_id);html=$(Cur_Cform_Hdr).html();_$_[868]==Cur_Cform_Hdr?(reset_html=_$_[869]+Msgs.addComment+_$_[77],$(Cur_Cform_Hdr).html(reset_html)):$(Cur_Cform_Hdr).html(_$_[1]);Cur_Cform_Hdr=_$_[870]+par_id;$(Cur_Cform_Hdr).html(html);$(_$_[871]).attr(_$_[699],Cform_Ins_ParID(par_id))},
Reset_Comment_Form=function(){html=$(Cur_Cform_Hdr).html();$(Cur_Cform_Hdr).html(_$_[1]);Cur_Cform_Hdr=_$_[868];$(Cur_Cform_Hdr).html(html);$(_$_[871]).attr(_$_[699],Cur_Cform_Url)},Cform_Ins_ParID=function(a){return a=_$_[872]+a+_$_[873],n_cform_url=Cur_Cform_Url.replace(/#%7B/,a),n_cform_url},Valid_Par_Id=function(a){return-1!=(r=a.indexOf(_$_[234]))&&(a=a.substring(r+1)),a};0<$(_$_[874]).length&&$(_$_[512]).hasClass(_$_[156])&&($(_$_[879]).each(function(){var a=$(this).html().replace(/\{/g,_$_[876]).replace(/#/g,
_$_[875]).replace(/\}/g,_$_[224]);$(this).html(a);a=$(this).children(_$_[877]);for(var g=0;g<a.length;g+=a.length+1)a.slice(g,g+a.length+1).wrapAll(_$_[878])}),$(_$_[874]).each(function(){var a=/(\r\n|\n|\r)/gm,g=$(_$_[880]).length?$(_$_[880]).text().replace(a,_$_[1]):_$_[881],f=(a=(f=$(this)).children(_$_[216]).html().replace(a,_$_[1]),f.find(_$_[882]).html());g===a&&(_$_[1]===$(_$_[883]).html()&&$(_$_[883]).html(desnya),$(_$_[884]).html(f),$(_$_[889]).each(function(){var a=$(this).attr(_$_[25]);
$(this).wrap(_$_[885]+a.replace(_$_[887],_$_[1]).replace(_$_[886],_$_[1])+_$_[888])}))}));var $postbody=$(_$_[402]).html(),$adsisi=$(_$_[890]),myrgx=/\[(full-post|left-post|right-post|left-side|right-side|hideadstitle)\]/g;if(/\[left-post\]/.test($postbody)?$(_$_[892]).addClass(_$_[891]):/\[right-post\]/.test($postbody)?$(_$_[892]).addClass(_$_[893]):/\[left-side\]/.test($postbody)?$(_$_[892]).addClass(_$_[894]):/\[right-side\]/.test($postbody)?$(_$_[892]).addClass(_$_[895]):/\[full-post\]/.test($postbody)&&
$(_$_[892]).addClass(_$_[896]),/\[hideadstitle\]/.test($postbody)&&$(_$_[892]).addClass(_$_[897]),myrgx.test($postbody)&&$(_$_[402]).html($postbody.replace(myrgx,_$_[1])),$postbody=$(_$_[402]).html(),/\[ads-post\]/.test($postbody)&&($(_$_[402]).html($postbody.replace(/\[ads-post\]/,_$_[898])),$(_$_[899]).html($adsisi.detach())),$postbody=$(_$_[402]).html(),$(_$_[900]).length&&!/\[hidetitleads\]/.test($postbody)&&($(_$_[402]).before(_$_[901]+(tbline?_$_[902]:_$_[1])+_$_[903]+(tbline?_$_[904]:_$_[1])+
_$_[642]),$(_$_[905]).html($(_$_[900]).detach()),!hecpt&&$(_$_[400]).length&&($(_$_[907]).prepend(_$_[906]+$(_$_[400]).html()+_$_[94]),$(_$_[400]).remove()),$(_$_[908]).length)){var len=$(_$_[909]).length?3:8;$(_$_[908]).RCWid({maxPosts:len,maxPostsPerTag:9,ShowImage:!1,ShowComment:!0,random:_$_[238]===blinest,tags:/(recent|random)/.test(blinest)?[]:null,ShowAuthor:!1})}if($(_$_[910]).length&&!/\[hidebottomads\]/.test($postbody)&&($(_$_[914]).before(_$_[911]+(bbline?_$_[902]:_$_[1])+_$_[22]+(bbline?
_$_[912]:_$_[1])+_$_[913]),$(_$_[915]).html($(_$_[910]).detach()),$(_$_[916]).length&&$(_$_[916]).RCWid({maxPosts:5,maxPostsPerTag:9,ShowImage:!0,ShowComment:!0,random:_$_[238]===btlinest,tags:/(recent|random)/.test(btlinest)?[]:null,ShowAuthor:!1})),/\[(hidetitleads|hideendads)\]/.test($postbody)&&$(_$_[402]).html($postbody.replace(/\[(hidetitleads|hideendads)\]/g,_$_[1])),$postbody=$(_$_[402]).html(),/\[next\]/.test($postbody)){$(_$_[851]).prepend(_$_[917]);$(_$_[914]).before(_$_[918]);$(_$_[402]).prepend(_$_[920]).append(_$_[919]);
var pbodyhtml=$(_$_[402]).html();$(_$_[402]).html(pbodyhtml.replace(/\[fnt\]/g,_$_[922]).replace(/\[next\]/g,_$_[921]).replace(/\[lnt\]/g,_$_[94]));var show_per_page=1,$this=$(_$_[851]);contentnya=$this.find(_$_[402]);number_of_items=contentnya.children().length;number_of_pages=Math.ceil(number_of_items/show_per_page);pageplace=$this.find(_$_[923]);curpagenya=$this.find(_$_[924]);perpagenya=$this.find(_$_[925]);curpagenya.val(0);perpagenya.val(show_per_page);for(var navigation_html=_$_[926],current_link=
0;number_of_pages>current_link;)navigation_html+=_$_[927]+current_link+_$_[928]+current_link+_$_[22]+(current_link+1)+_$_[77],current_link++;navigation_html+=_$_[929];pageplace.html(navigation_html);pageplace.find(_$_[931]).addClass(_$_[930]);contentnya.children().css(_$_[180],_$_[932]);contentnya.children().slice(0,show_per_page).css(_$_[180],_$_[181]);var go_to_page=function(a){var g=parseInt(perpagenya.val());start_from=a*g;end_on=start_from+g;contentnya.children().css(_$_[180],_$_[932]).slice(start_from,
end_on).css(_$_[180],_$_[181]);$this.find(_$_[934]+a+_$_[935]).addClass(_$_[930]).siblings(_$_[933]).removeClass(_$_[930]);curpagenya.val(a);$(_$_[205]).animate({scrollTop:$(_$_[402]).offset().top-80},1E3)};$this.find(_$_[937]).on(_$_[9],function(){var a=$this.find(_$_[933]);return new_page=parseInt(curpagenya.val())-1,1==a.prev(_$_[936]).length&&go_to_page(new_page),!1});$this.find(_$_[938]).on(_$_[9],function(){var a=$this.find(_$_[933]);return new_page=parseInt(curpagenya.val())+1,1==a.next(_$_[936]).length&&
go_to_page(new_page),!1});$this.find(_$_[936]).on(_$_[9],function(){var a=$(this).attr(_$_[939]);return go_to_page(a),!1});$this.find(_$_[940]).on(_$_[9],function(){return $(this).attr(_$_[939]),contentnya.children().css(_$_[180],_$_[181]),pageplace.hide(),$(_$_[205]).animate({scrollTop:$(_$_[402]).offset().top-80},1E3),!1})}$(_$_[954]).each(function(){var a=$(this).attr(_$_[699]);$(this).attr(_$_[699],a.replace(/\/s[0-9]+(\-c)?\//,_$_[953])).addClass(_$_[426])});$(_$_[507]).append(_$_[955]);$(_$_[956]).append($(_$_[417]));
$(_$_[417]).myTab();1==$(_$_[957]).length&&$(_$_[958]).hide();$(_$_[964]).each(function(){var a=$(this),g=a.attr(_$_[44]),f=a.parent(_$_[28]),b=a.parents(_$_[959]);null==g&&_$_[1]==g||!/\{featured\}/.exec(g)||(a.attr(_$_[44],g.replace(/\{featured\}/,_$_[1])),f.length?f.addClass(_$_[960]):a.addClass(_$_[960]),b.length&&(b.addClass(_$_[556]),a=b.find(_$_[961]).text(),b.find(_$_[963]).append(_$_[962]+a+_$_[105])))});var txtnyaaa=$(_$_[402]).html(),imgjd=[],pfeat=(imgjd=/<amp-img\s+[^>]*src="([^"]*)"[^>]*>/.exec(txtnyaaa),
$(_$_[963]));if(pfeat.length)$(_$_[963]).each(function(){$(_$_[965]).append($(this))}),1<pfeat.length&&($(_$_[965]).wrapInner(_$_[966]),$(_$_[967]).owlCarousel({nav:!0,navText:[_$_[1],_$_[1]],loop:!0,responsiveClass:!0,autoplayHoverPause:!0,smartSpeed:500,items:1,responsiveRefreshRate:500}).addClass(_$_[561]));else if(null!=imgjd&&480>=imgjd.index&&fpost){var img=$(_$_[964]).first(),par=img.parent(_$_[28]),pars=img.parents(_$_[959]),gpars=img.parents(_$_[968]),pars2=img.parents(_$_[969]);if(!gpars.length){if($(_$_[965]).append(par.length?
par:img),pars2.addClass(_$_[556]),pars.length){var text=pars.find(_$_[961]).text();$(_$_[970]).append(_$_[962]+text+_$_[105]);pars.addClass(_$_[556])}$(_$_[971]).length&&$(_$_[971]).removeAttr(_$_[78])}}var link=$(_$_[852]).attr(_$_[108]);$(_$_[401]).after(_$_[974]+link+_$_[975]);$(_$_[977]).click(function(){var a=$(this);return a.hasClass(_$_[18])?($(_$_[976]).hide(),a.removeClass(_$_[18])):(a.addClass(_$_[18]),$(_$_[976]).show().children().focus().select()),!1});$(_$_[979]).addClass(_$_[978])}
$(_$_[980]).each(function(){$(this).html($(this).html().replace(rgx[16],_$_[1]))});var $outer=$(_$_[981]),$contact=$(_$_[982]);$(_$_[984]).click(function(){return $contact.hasClass(_$_[583])||($contact.addClass(_$_[583]),$outer.addClass(_$_[983])),!1});$(_$_[985]).click(function(){return $contact.removeClass(_$_[583]),$outer.removeClass(_$_[983]),!1});$(document).on(_$_[9],function(a){$(a.target).is(_$_[986])||($contact.removeClass(_$_[583]),$outer.removeClass(_$_[983]))});
$(_$_[988]).each(function(){var a=$(this);a.parents(_$_[503]);a=a.html();$(_$_[987]).append(a)});
$(_$_[1009]).one(_$_[590],function(){var a=$(this),g=a.find(_$_[35]),f=g.text();if(/grid/g.test(f))f=f.replace(/grid\//g,_$_[1]),a.addClass(_$_[581]),g.RCWid({maxPosts:4,random:_$_[238]===f,review:!hrev,ShowTags:!!/(recent|random)/.test(f),tags:/(recent|random)/.test(f)?null:f.split(_$_[217])}).addClass(_$_[989]),g.append(_$_[990]+(_$_[238]===f?_$_[991]:_$_[1])+_$_[992]+(_$_[220]===f?_$_[1]:_$_[221]+f)+_$_[222]+Npage+_$_[993]).addClass(_$_[132]);else if(/mcarousel/g.test(f)){var b=a.parents(_$_[987]);
f=f.replace(/mcarousel\//g,_$_[1]);a.addClass(_$_[581]);g.RCWid({maxPosts:9,random:_$_[238]===f,review:!hrev,auto:aplay,postType:b.length?_$_[1]:_$_[234],ShowTags:!!/(recent|random)/.test(f),tags:/(recent|random)/.test(f)?null:f.split(_$_[217])}).addClass(_$_[989]);g.append(_$_[990]+(_$_[238]===f?_$_[991]:_$_[1])+_$_[992]+(_$_[220]===f?_$_[1]:_$_[221]+f)+_$_[222]+Npage+_$_[993]).addClass(_$_[994])}else if(/mtab/g.test(f)){b=(f=f.replace(/mtab\//g,_$_[1])).split(_$_[217]);f=_$_[995];for(var k=0;k<
b.length;k++)f+=_$_[256]+b[k]+_$_[22]+b[k]+_$_[94];g.html(f+_$_[94]);g.find(_$_[996]).myTab();a.addClass(_$_[581]);g.find(_$_[260]).each(function(){var a=$(this).text();$(this).RCWid({maxPosts:4,review:!hrev,tags:a.split(_$_[217])}).addClass(_$_[989]);$(this).append(_$_[997]+a+_$_[222]+Npage+_$_[993])});g.addClass(_$_[998])}else/mbig/g.test(f)?(f=f.replace(/mbig\//g,_$_[1]),a.addClass(_$_[581]),g.RCWid({maxPosts:7,random:_$_[238]===f,maxPostsPerTag:/(recent|random)/.test(f)||1==f.split(_$_[217]).length?
7:4,tags:/(recent|random)/.test(f)?null:f.split(_$_[217]),fbig:!0,review:!hrev,summary:100}),g.append(_$_[990]+(_$_[238]===f?_$_[991]:_$_[1])+_$_[992]+(_$_[220]===f?_$_[1]:_$_[221]+f)+_$_[222]+Npage+_$_[993]).addClass(_$_[999])):/links/g.test(f)&&(a.addClass(_$_[581]),g.html(_$_[1]),g.addClass(_$_[1E3]),a=$(_$_[1001]),$(_$_[1002]).hide(),a.each(function(){var a=$(this).children(_$_[216]).html(),b=$(this).children(_$_[835]).html();g.append(_$_[1003]+a+_$_[1004]+b+_$_[642])}),g.find(_$_[835]).each(function(){if(texnya=
$(this).text(),/gridpost/g.test(texnya)){var a=$(this).parents(_$_[987]),b=texnya.replace(/gridpost\//g,_$_[1]).replace(/(\r\n|\n|\r)/gm,_$_[1]);$(this).RCWid({maxPosts:4,random:_$_[238]===b,ShowTags:!!/(recent|random)/.test(b),review:!hrev,postType:a.length?_$_[1]:_$_[234],tags:/(recent|random)/.test(b)?null:b.split(_$_[217])}).addClass(_$_[989]);(a=$(this).parent(_$_[1005])).addClass(_$_[1006]);_$_[238]!==b&&(a.find(_$_[216]).wrapInner(_$_[1007]+(_$_[220]===b?_$_[1]:_$_[221]+b)+_$_[222]+Npage+_$_[224]),
a.find(_$_[216]).append(_$_[1008]+(_$_[220]===b?_$_[1]:_$_[221]+b)+_$_[222]+Npage+_$_[22]+mtx+_$_[77]))}}))});$(_$_[1011]).html($(_$_[1010]).html());$(_$_[1013]).html($(_$_[1012]).html());$(_$_[1015]).click(function(){var a=$(this).parent(_$_[35]).children(_$_[37]);return a.is(_$_[1014])?(a.slideDown(),$(this).addClass(_$_[18])):(a.slideUp(),$(this).removeClass(_$_[18])),!1});$(_$_[987]).css({"max-height":$(window).height()-140});
var maxSummaryLength=sumLength,olderLink=_$_[1016]+ptx+_$_[1017],newerLink=_$_[1018]+ntx+_$_[1017],defaultImage=_$_[776],getThumb=function(a,g){var f=g;var b=a.content.$t;try{f=a.media$thumbnail.url}catch(k){f=rgx[6].test(b)||rgx[8].test(b)?(f=rgx[6].exec(rgx[6]),b=rgx[8].exec(b),_$_[53]+(null!=f?f[5]:b[3])+_$_[51]):rgx[5].test(b)?rgx[5].exec(b)[4]:g}return f},setLink=function(a,g,f,b){var k=b.published.$t.match(/\d+/g);k=new Date(k[0],k[1]-1,k[2],k[3],k[4],k[5]);f=getThumb(b,f);var l=$(a).attr(_$_[27]);
if((p=(p=_$_[108]in b?b.content.$t:_$_[109]in b?b.summary.$t:_$_[1]).replace(rgx[15],_$_[1]).replace(rgx[16],_$_[1]).replace(/"/g,_$_[73])).length>maxSummaryLength)var m=(p=p.substring(0,maxSummaryLength)).lastIndexOf(_$_[76]),p=p.substring(0,m)+_$_[115];g=g.replace(/\[title\]/g,b.title.$t).replace(/\[date\]/g,k.toLocaleDateString().replace(/\[datetime\]/g,k.toLocaleString().replace(/\[summary\]/g,p)).replace(/\[thumburl\]/g,f)).replace(/\[url\]/g,l);k=_$_[1];_$_[1]!=f&&(k=_$_[1019]+f+_$_[22]);g=
g.replace(/\[amp-img\]/g,k);$(a).replaceWith(g)},setOlderLink=function(a){setLink(_$_[1020],olderLink,defaultImage,a)},setNewerLink=function(a){setLink(_$_[1021],newerLink,defaultImage,a)};$(_$_[1024]).each(function(){var a=$(this).attr(_$_[44]),g=$(this).attr(_$_[1022]);$(_$_[1023]).replaceText(a,g)});var target,scroll,lastScrollTop=0;
$(window).on(_$_[1025],function(){var a=$(this).scrollTop();fixM&&(a>=$(_$_[1026]).height()+60?($(_$_[1028]).addClass(_$_[1027]),lastScrollTop<a?$(_$_[1026]).hasClass(_$_[1029])&&$(_$_[1026]).removeClass(_$_[1029]):$(_$_[1026]).addClass(_$_[1029]),lastScrollTop=a):$(_$_[1028]).removeClass(_$_[1027]),$(_$_[1031]).hasClass(_$_[1030])||$(_$_[1031]).addClass(_$_[1030]));sSide&&960<$(this).width()&&(1<$(_$_[206]).width()&&stickside($(_$_[206]),_$_[1032],a),1<$(_$_[1033]).width()&&stickside($(_$_[1033]),
_$_[1032],a),$(_$_[1031]).hasClass(_$_[1034])||$(_$_[1031]).addClass(_$_[1034]));var g,f,b,k=$(_$_[518]).length;if($(_$_[1035]).length<k){var l=1<=a;$(_$_[518]).each(function(){if(!$(this).hasClass(_$_[275])){var a=$(this),b=a.children(_$_[835]),f=a.find(_$_[844]),g=b.text();l&&ldwid(f,a,b,g)}})}if($(_$_[1036]).length||fbsdk(),$(_$_[354]).length&&$(_$_[509]).hasClass(_$_[1037])&&$(_$_[1038]).length&&!$(_$_[354]).hasClass(_$_[1039])&&((f=(g=document).createElement(_$_[261])).src=_$_[95]+dsqsn+_$_[1040],
f.setAttribute(_$_[1041],+new Date),(g.head||g.body).appendChild(f),$(_$_[354]).addClass(_$_[1039])),$(_$_[1042]).length&&$(_$_[1043]).length&&!$(_$_[1042]).hasClass(_$_[1044])){var m=$(_$_[1042]).attr(_$_[44]);var p=window.SPOTIM={};g=document;f=_$_[1045];var u=(b=g.getElementsByTagName(_$_[261]))[b.length-1].parentNode;p.spotId=m;b=p.parentElement=u;(p=g.createElement(_$_[261])).type=_$_[408];p.async=!0;p.src=(_$_[410]===g.location.protocol?_$_[409]:_$_[80])+_$_[1046]+f;(b||g.body||g.head).appendChild(p);
$(_$_[1042]).addClass(_$_[1044])}$(_$_[1047]).length&&!$(_$_[1048]).length&&socialct($(_$_[851]));(k=$(_$_[146]).attr(_$_[44]))&&_$_[1]!=k&&$(_$_[512]).hasClass(_$_[156])&&!$(_$_[1050]).hasClass(_$_[1049])&&($(_$_[1050]).addClass(_$_[1049]),$.getJSON(_$_[1051]+encodeURIComponent(k)+_$_[1052],function(a){1<(a=parseInt(a.feed.openSearch$totalResults.$t))?$.getJSON(_$_[1053]+(a-1)+_$_[1054],function(a){setNewerLink(a.feed.entry[0]);1<parseInt(a.feed.openSearch$totalResults.$t)-parseInt(a.feed.openSearch$startIndex.$t)&&
setOlderLink(a.feed.entry[2])}):$.getJSON(_$_[1055],function(a){setOlderLink(a.feed.entry[0])})}));$(_$_[1056]).length&&!$(_$_[1057]).length&&$(_$_[1056]).each(function(){$(this).attr(_$_[78],_$_[1058]+$(this).attr(_$_[49])+_$_[1059]);$(this).removeAttr(_$_[49]);$(this).addClass(_$_[1060])});250<=a?$(_$_[1062]).addClass(_$_[1061]):$(_$_[1062]).removeClass(_$_[1061]);shreco&&$(_$_[1063]).length&&$(_$_[512]).hasClass(_$_[156])&&($(_$_[1064]).length||($(_$_[981]).append(_$_[1065]+recotx+_$_[1066]),$(_$_[1067]).RCWid({maxPosts:2,
maxPostsPerTag:4,ShowComment:!0,ShowImage:!0,ShowDesc:!1,summary:100,ShowAuthor:hauthor}),$(_$_[1070]).on(_$_[9],function(){return $(_$_[1064]).hasClass(_$_[1068])?$(_$_[1064]).removeClass(_$_[1068]).addClass(_$_[1069]):$(_$_[1064]).addClass(_$_[1068]),!1})),a>$(_$_[1071]).offset().top-400&&a<$(_$_[1072]).offset().top-$(_$_[1072]).height()&&960<$(this).width()?$(_$_[1064]).addClass(_$_[1068]):$(_$_[1064]).removeClass(_$_[1068]));shrel&&1<a&&!$(_$_[1074]).hasClass(_$_[1073])&&$(_$_[1074]).RCWid({maxPosts:_$_[359]===
relst?mx.rl:_$_[1076]===relst?mx.fb1:6,maxPostsPerTag:6,auto:aplay,postType:_$_[359]===relst?_$_[234]:_$_[1],ShowDesc:_$_[1076]===relst}).addClass(_$_[1075]+relst)});$(_$_[1063]).each(function(){var a=1,g=$(this);var f=$(this).text().replace(/(\r\n|\n|\r)/gm,_$_[1]);$(_$_[1079]).each(function(){var b=$(this);var k=b.attr(_$_[44]).replace(/(\r\n|\n|\r)/gm,_$_[1]);a=b.attr(_$_[1077]);f!==k||g.attr(_$_[1078])||g.attr(_$_[1078],a)})});
$(_$_[1084]).on(_$_[9],function(a){location.pathname.replace(/^\//,_$_[1])==this.pathname.replace(/^\//,_$_[1])&&location.hostname==this.hostname&&(target=(target=$(this.hash)).length?target:$(_$_[1080]+this.hash.slice(1)+_$_[935])).length&&(_$_[1081]==typeof document.body.style.transitionProperty?(a.preventDefault(),(a=$(document).height()-$(window).height())<(scroll=target.offset().top)&&(scroll=a),$(_$_[153]).css({"margin-top":$(window).scrollTop()-scroll+_$_[297],transition:_$_[1083]}).data(_$_[1082],
!0)):$(_$_[205]).animate({scrollTop:scroll},1E3))});$(_$_[153]).on(_$_[1085],function(a){a.target==a.currentTarget&&!0===$(this).data(_$_[1082])&&($(this).removeAttr(_$_[78]).data(_$_[1082],!1),$(_$_[205]).scrollTop(scroll))});
$(window).on(_$_[1086],function(){$(_$_[1088]).each(function(){680>$(this).width()?$(this).addClass(_$_[1087]):$(this).removeClass(_$_[1087])});680>(m=(g=$(_$_[154])).width())?g.addClass(_$_[1089]):g.removeClass(_$_[1089]);$(_$_[1090]).length||$(_$_[1092]).append($(_$_[1091]));$(_$_[1093]).length&&(m=$(_$_[1094]).width(),$(_$_[1095]).css({width:m}));var a=$(window).width(),g=$(_$_[1096]).height(),f=$(_$_[1097]).height(),b=$(_$_[207]).height(),k=$(_$_[1098]).height(),l=$(_$_[209]).height(),m=$(_$_[1033]).width();
960<a?(g<(a=f+b+k+l)?$(_$_[1096]).css(_$_[1099],a+_$_[297]):$(_$_[1096]).css(_$_[1099],_$_[301]),100>m&&$(_$_[1033]).addClass(_$_[556])):($(_$_[1096]).css(_$_[1099],_$_[301]),100<m&&$(_$_[1033]).removeClass(_$_[556]))}).trigger(_$_[1086]);
var Bamboo=function(a,g){function f(b){for(i in this.options={menu:!0,breakpoint:1E3,menuWidth:300,headerHeight:50,snapThreshold:null,resize:null},b)this.options[i]=b[i];this.resizeSite();$(a).on(q,this.resizeSite.bind(this));m.on(h,this._move.bind(this));l.on(y,this._end.bind(this))}$(_$_[1106]);var b,k,l=$(_$_[981]),m=l.parent().children(_$_[1107]),p=(k=!1,_$_[1108]in a||a.DocumentTouch&&g instanceof DocumentTouch?(k=!0,$(_$_[153]).addClass(_$_[1109])):$(_$_[153]).addClass(_$_[16]),k),u=(b=0,navigator.userAgent.match(/(iPhone|iPod)/i)&&
-1!=navigator.userAgent.indexOf(_$_[1110])&&-1==navigator.userAgent.indexOf(_$_[1111])&&(b=60),_$_[1112]in a.navigator&&a.navigator.standalone&&(b=0),b),q=_$_[1114]in a?_$_[1115]:_$_[1086],y=p?_$_[1120]:_$_[1121];return f.prototype={info:{},x:0,dx:0,ox:null,tgt:null,desktop:!1,dimensions:function(){return[this.info.docWidth,this.info.docHeight]},offset:function(){return u},resizeSite:function(){this.info.docHeight=$(a).height();this.info.docWidth=$(a).width();this.layout();this.snapThreshold=null===
this.options.snapThreshold?Math.round(.25*this.info.docWidth):/%/.test(this.options.snapThreshold)?Math.round(this.info.docWidth*this.options.snapThreshold.replace(_$_[71],_$_[1])/100):this.options.snapThreshold;this.options.resize&&this.options.resize()},layout:function(){this.desktop=!(this.info.docWidth<this.options.breakpoint)},_move:function(a){if(this.initiated&&!this.desktop&&this.options.menu){var b=p?a.originalEvent.touches[0]:a;this.stepsX+=Math.abs(b.pageX-this.pointX);this.stepsY+=Math.abs(b.pageY-
this.pointY);10>this.stepsX&&10>this.stepsY||(!this.directionLocked&&this.stepsY>this.stepsX?this.initiated=!1:(a.preventDefault(),this.directionLocked=!0,this.ox&&(a=parseInt(b.pageX)-this.ox,this.dx=a-this.x,this.x=a,this._moveContainer(a))))}},_end:function(a){this.initiated&&!this.desktop&&this.options.menu&&(a=parseInt((p?a.originalEvent.changedTouches[0]:a).pageX)-parseInt(this.ox),0>=this.dx&&!this.tgt.is(_$_[1123])?this._animateTo(a,0):this._animateTo(a,this.options.menuWidth),0===this.dx&&
0===a&&this.tgt.is(_$_[1106])&&this._animateTo(this.options.menuWidth,this.options.menuWidth),this.ox=null,this.dx=0,this.initiated=!1)},_animateTo:function(a,b){m.css({"transition-duration":Math.floor(100*a/this.snapThreshold)+_$_[1124],transform:_$_[1125]+b+_$_[1126]+d});this._toggleCover(b)},_moveContainer:function(a){m.css({transform:_$_[1125]+a+_$_[1126]+d})},_toggleCover:function(a){a>this.options.menuWidth-50?(l.addClass(_$_[1127]),$(_$_[1129]).addClass(_$_[1128])):(l.removeClass(_$_[1127]),
$(_$_[1129]).removeClass(_$_[1128]))}},f}
